import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { Controller, type UhpAdapter } from '../src/controller.js';
import { JsonStore } from '../src/store.js';

const dirs:string[]=[];
async function setup(adapter?:Partial<UhpAdapter>) { const dir=await mkdtemp(join(tmpdir(),'foreman-'));dirs.push(dir);const store=new JsonStore(join(dir,'state.json'));const calls:{input:any}[]=[];const uhp:UhpAdapter={submit:async input=>{calls.push({input});return {externalId:'external-1',status:'completed',result:{ok:true}};},cancel:async()=>({status:'cancelled'}),...adapter};return {store,controller:new Controller(store,uhp),calls}; }
afterEach(async()=>{await Promise.all(dirs.splice(0).map(d=>rm(d,{recursive:true,force:true})));});

describe('controller persistence and state transitions',()=>{
  it('validates role configuration before creating submission intent',async()=>{const {controller,store}=await setup();const p:any=await controller.createProject('Example');const t:any=await controller.createTask(p.id,'Task');const r:any=await controller.createRun(t.id);await expect(controller.assign(r.id,'worker','do work',{provider:'invalid',model:'bad'})).rejects.toThrow('Unsupported');expect((await store.load()).projects[0]!.tasks[0]!.runs[0]!.assignments).toHaveLength(0);});
  it('queues active-run guidance in sequence until acknowledged',async()=>{const {controller,store}=await setup();const p:any=await controller.createProject('Example');const t:any=await controller.createTask(p.id,'Task');const r:any=await controller.createRun(t.id);await controller.assign(r.id,'worker','work');await store.mutate(state=>{state.projects[0]!.tasks[0]!.runs[0]!.assignments[0]!.status='running';});const a:any=await controller.addGuidance(r.id,'First');const b:any=await controller.addGuidance(r.id,'Second');expect([a.status,b.status]).toEqual(['queued','queued']);expect([a.sequence,b.sequence]).toEqual([1,2]);await controller.acknowledgeGuidance(a.id,'replan');const state=await controller.state();expect(state.projects[0]!.tasks[0]!.runs[0]!.guidance[0]!.acknowledgment).toBe('replan');});
  it('persists the idempotency intent before submit and saves returned identifiers',async()=>{let path='';let observed:any;const {controller,store}=await setup({submit:async()=>{observed=JSON.parse(await readFile(path,'utf8'));return {externalId:'ext',sessionId:'sess',responseId:'resp',status:'completed',outputText:'done'};}});path=store.filePath;const p:any=await controller.createProject('Example');const t:any=await controller.createTask(p.id,'Task');const r:any=await controller.createRun(t.id);const a:any=await controller.assign(r.id,'worker','work');const saved=observed.projects[0].tasks[0].runs[0].assignments[0];expect(saved.status).toBe('submitting');expect(saved.idempotencyKey).toBe(a.idempotencyKey);expect(a.externalId).toBe('ext');expect(a.sessionId).toBe('sess');expect(a.responseId).toBe('resp');expect(a.status).toBe('succeeded');const reloaded=await new JsonStore(path).load();expect(reloaded.projects[0]!.tasks[0]!.runs[0]!.assignments[0]!.externalId).toBe('ext');});
  it('recovers an uncertain submission with its original idempotency key',async()=>{const {controller,store}=await setup({submit:async()=>{throw new Error('offline');}});const p:any=await controller.createProject('Example');const t:any=await controller.createTask(p.id,'Task');const r:any=await controller.createRun(t.id);await expect(controller.assign(r.id,'worker','work')).rejects.toThrow('offline');const s=await store.load();const key=s.projects[0]!.tasks[0]!.runs[0]!.assignments[0]!.idempotencyKey;let recoveryKey='';const recovered=new Controller(store,{submit:async input=>{recoveryKey=input.idempotencyKey;return {externalId:'ext',status:'completed'};},cancel:async()=>({status:'cancelled'})});await recovered.recover();expect(recoveryKey).toBe(key);expect((await store.load()).projects[0]!.tasks[0]!.runs[0]!.assignments[0]!.status).toBe('succeeded');});
});
