import { mkdir, mkdtemp, rm, writeFile } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createServer, type Server } from 'node:http';
import { once } from 'node:events';
import { createHash } from 'node:crypto';
import { afterEach, describe, expect, it } from 'vitest';
import { Controller, type UhpAdapter } from '../src/controller.js';
import { JsonStore } from '../src/store.js';
import { findSavedProjectForRepository, saveWorkspaceSetup, validateWorkspaceSetup } from '../src/workspace-setup.js';

const dirs:string[]=[];
const servers:Server[]=[];
afterEach(async()=>{await Promise.all([...servers.splice(0).map(server=>new Promise<void>(resolve=>server.close(()=>resolve()))),...dirs.splice(0).map(dir=>rm(dir,{recursive:true,force:true}))]);});

describe('project Planner workflow',()=>{
  it('persists one project conversation, creates separate tasks without starting workers, and isolates repositories',async()=>{
    const dir=await mkdtemp(join(tmpdir(),'foreman-project-planner-'));dirs.push(dir);const store=new JsonStore(join(dir,'state.json'));
    const submitted:Array<{roleId:string;projectId:string;prompt:string;config:Record<string,unknown>}>=[];
    const plannerReplies=[`I’ll check the requested behavior, then propose separate implementation tasks.\n${JSON.stringify({reply:'I split this into two independent tasks.',tasks:[
      {ref:'readme',title:'Update README',goal:'Document the requested behavior.',suggestedAllowedPaths:['README.md'],validationCriteria:['README renders and links resolve.']},
      {ref:'endpoint',title:'Add REST endpoint',goal:'Implement the requested endpoint.',suggestedAllowedPaths:['src/http/'],validationCriteria:['Endpoint tests pass.'],dependsOn:['readme']}
    ]})}`,JSON.stringify({reply:'The README task is ready to start.'}),JSON.stringify({reply:'A separate repository conversation.'}),JSON.stringify({reply:'New model, same repository.'})];
    const adapter:UhpAdapter={submit:async input=>{submitted.push({roleId:input.roleId,projectId:input.projectId,prompt:input.prompt,config:input.config});return {externalId:`external-${submitted.length}`,responseId:`response-${submitted.length}`,sessionId:`session-${submitted.length}`,status:'completed',outputText:plannerReplies.shift()??'Fixture reply'};},cancel:async()=>({status:'cancelled'})};
    await store.mutate(state=>{for(const role of state.roles){role.enabled=true;role.availableConfigs=[{harnessId:'fixture',model:'model-fixture'},{harnessId:'fixture',model:'other-model'}];role.config={harnessId:'fixture',model:'model-fixture'};}});
    const controller=new Controller(store,adapter);const first:any=await controller.createProject('Repository A'),second:any=await controller.createProject('Repository B');
    await controller.selectRoleConfig('planner',{harnessId:'fixture',model:'other-model'},second.id);
    const response=await controller.sendProjectPlannerMessage(first.id,'Update this node README and add a REST endpoint.');const initialSessionId=response.project.plannerSession?.localId;
    expect(response.createdTasks).toHaveLength(2);expect(response.createdTasks.map(task=>task.id)).toEqual(expect.arrayContaining([expect.stringMatching(/^tsk_/),expect.stringMatching(/^tsk_/)]));
    expect(response.createdTasks[0]).toMatchObject({title:'Update README',goal:'Document the requested behavior.',suggestedAllowedPaths:['README.md'],validationCriteria:['README renders and links resolve.']});
    expect(response.createdTasks[1]!.dependsOn).toEqual([response.createdTasks[0]!.id]);
    expect((await controller.state()).projects.find(project=>project.id===first.id)?.tasks).toHaveLength(2);
    expect(submitted.map(call=>call.roleId)).toEqual(['planner']);
    expect((await controller.state()).projects.flatMap(project=>project.tasks.flatMap(task=>task.runs))).toHaveLength(0);

    const restarted=new Controller(new JsonStore(store.filePath),adapter);await restarted.sendProjectPlannerMessage(first.id,'Keep the README task concise.');
    await restarted.sendProjectPlannerMessage(second.id,'Help me plan this different repository.');
    const stableSession=(await new JsonStore(store.filePath).load()).projects.find(project=>project.id===first.id)?.plannerSession?.localId;expect(stableSession).toBe(initialSessionId);
    await restarted.selectRoleConfig('planner',{harnessId:'fixture',model:'other-model'},first.id);const rotated=await restarted.sendProjectPlannerMessage(first.id,'Continue after changing Planner model.');
    const state=await new JsonStore(store.filePath).load();const a=state.projects.find(project=>project.id===first.id)!,b=state.projects.find(project=>project.id===second.id)!;
    expect(a.plannerMessages?.map(message=>message.role)).toEqual(['user','planner','user','planner','user','planner']);
    expect(a.plannerSession?.projectId).toBe(first.id);expect(a.plannerSession?.uhpSessionId).toBe('session-4');
    expect(b.plannerSession?.projectId).toBe(second.id);expect(b.plannerSession?.uhpSessionId).toBe('session-3');
    expect(a.plannerSession?.config).toMatchObject({harnessId:'fixture',model:'other-model'});expect(b.plannerSession?.config).toMatchObject({harnessId:'fixture',model:'other-model'});
    expect(rotated.project.plannerSession?.localId).not.toBe(initialSessionId);expect(rotated.project.plannerSession?.config).toMatchObject({harnessId:'fixture',model:'other-model'});
    expect(submitted[1]!.projectId).toBe(first.id);expect(submitted[1]!.prompt).toContain('Update this node README');expect(submitted[1]!.prompt).not.toContain('different repository');
    expect(submitted[1]!.prompt).toContain(response.createdTasks[0]!.id);expect(submitted[1]!.prompt.length).toBeLessThan(15_000);
    expect(submitted[2]!.projectId).toBe(second.id);expect(submitted[2]!.prompt).toContain('different repository');expect(submitted[2]!.prompt).not.toContain('Update this node README');
    expect(submitted[1]!.config).not.toHaveProperty('previousResponseId');expect(submitted[2]!.config).not.toHaveProperty('previousResponseId');
    expect(submitted.slice(1).every(call=>call.roleId==='planner')).toBe(true);
  });

  it('keeps every Planner message visible while bounding prompts to recent history and the stable task index',async()=>{
    const dir=await mkdtemp(join(tmpdir(),'foreman-long-planner-'));dirs.push(dir);const store=new JsonStore(join(dir,'state.json')),prompts:string[]=[];
    const adapter:UhpAdapter={submit:async input=>{prompts.push(input.prompt);return {externalId:`long-${prompts.length}`,responseId:`long-response-${prompts.length}`,sessionId:'long-session',status:'completed',outputText:'Recorded Planner reply.'};},cancel:async()=>({status:'cancelled'})};
    await store.mutate(state=>{for(const role of state.roles){role.enabled=true;role.availableConfigs=[{harnessId:'fixture',model:'model-fixture'}];role.config={harnessId:'fixture',model:'model-fixture'};}});
    const controller=new Controller(store,adapter),project:any=await controller.createProject('Long Planner history'),task:any=await controller.createTask(project.id,{title:'Retain task identity',goal:'Keep the stable task visible in bounded Planner context.',suggestedAllowedPaths:['README.md'],validationCriteria:['README check passes']});
    let latestRequest='';for(let turn=1;turn<=18;turn++){latestRequest=`request-${turn} `+'x'.repeat(9000);await controller.sendProjectPlannerMessage(project.id,latestRequest);}
    const saved=(await controller.state()).projects.find(value=>value.id===project.id)!;expect(saved.plannerMessages).toHaveLength(36);expect(saved.plannerMessages?.filter(message=>message.role==='user').map(message=>message.text)).toHaveLength(18);expect(saved.plannerMessages?.at(-2)?.text).toBe(latestRequest);expect(prompts).toHaveLength(18);
    const finalPrompt=prompts.at(-1)!;expect(Buffer.byteLength(finalPrompt,'utf8')).toBeLessThanOrEqual(24_000);expect(finalPrompt).toContain(`request-18`);expect(finalPrompt).toContain(task.id);expect(finalPrompt).not.toContain('request-1 ');
  });

  it('rejects a malformed proposal batch without creating a partial task set',async()=>{
    const dir=await mkdtemp(join(tmpdir(),'foreman-project-planner-'));dirs.push(dir);const store=new JsonStore(join(dir,'state.json'));
    const adapter:UhpAdapter={submit:async()=>({externalId:'bad-proposal',status:'completed',outputText:JSON.stringify({reply:'Malformed proposal.',tasks:[{title:'Valid first task',goal:'A goal',suggestedAllowedPaths:['README.md'],validationCriteria:['Pass']},{title:'Invalid second task',goal:'A goal',suggestedAllowedPaths:['../outside'],validationCriteria:['Pass']}]})}),cancel:async()=>({status:'cancelled'})};
    await store.mutate(state=>{for(const role of state.roles){role.enabled=true;role.availableConfigs=[{harnessId:'fixture',model:'model-fixture'}];role.config={harnessId:'fixture',model:'model-fixture'};}});
    const controller=new Controller(store,adapter),project:any=await controller.createProject('Atomic proposal');
    const result=await controller.sendProjectPlannerMessage(project.id,'Please create two tasks.');expect(result.proposalError).toContain('Invalid repository path');expect(result.createdTasks).toHaveLength(0);
    expect((await controller.state()).projects.find(value=>value.id===project.id)?.tasks).toHaveLength(0);
  });

  it('keeps legacy run Planner conversations attached to their original run',async()=>{
    const dir=await mkdtemp(join(tmpdir(),'foreman-project-planner-'));dirs.push(dir);const store=new JsonStore(join(dir,'state.json'));
    const adapter:UhpAdapter={submit:async()=>({externalId:'new-planner',responseId:'new-response',sessionId:'new-session',status:'completed',outputText:'New project conversation.'}),cancel:async()=>({status:'cancelled'})};
    await store.mutate(state=>{for(const role of state.roles){role.enabled=true;role.availableConfigs=[{harnessId:'fixture',model:'model-fixture'}];role.config={harnessId:'fixture',model:'model-fixture'};}});
    const controller=new Controller(store,adapter),project:any=await controller.createProject('Legacy project'),task:any=await controller.createTask(project.id,'Old task'),run:any=await controller.createRun(task.id);
    await store.mutate(state=>{const old=state.projects[0]!.tasks[0]!.runs[0]!;old.assignments.push({id:'old-planner-turn',roleId:'planner',status:'succeeded',requestedConfig:{harnessId:'fixture',model:'model-fixture'},prompt:'Old run planner',result:'Old run plan',createdAt:new Date().toISOString()} as any);old.guidance.push({id:'old-guidance',sequence:1,text:'Old run request',status:'delivered',plannerAssignmentId:'old-planner-turn',plannerReply:'Old run plan',createdAt:new Date().toISOString()});});
    await controller.sendProjectPlannerMessage(project.id,'Start a distinct project level conversation.');
    const saved=await new JsonStore(store.filePath).load(),savedProject=saved.projects.find(value=>value.id===project.id)!,savedRun=savedProject.tasks[0]!.runs[0]!;
    expect(savedRun.id).toBe(run.id);expect(savedRun.guidance[0]?.plannerReply).toBe('Old run plan');expect(savedRun.assignments.find(value=>value.id==='old-planner-turn')?.result).toBe('Old run plan');
    expect(savedProject.plannerMessages?.map(message=>message.text)).toEqual(['Start a distinct project level conversation.','New project conversation.']);
  });

  it('validates an opened Git repository, then starts one selected task into its own run and evidence path',async()=>{
    const dir=await mkdtemp(join(tmpdir(),'foreman-open-repo-'));dirs.push(dir);const repo=join(dir,'repo');await (await import('node:fs/promises')).mkdir(repo);
    execFileSync('git',['-C',repo,'init','--quiet']);execFileSync('git',['-C',repo,'config','user.name','Fixture']);execFileSync('git',['-C',repo,'config','user.email','fixture@example.test']);await writeFile(join(repo,'README.md'),'Fixture repository\n');execFileSync('git',['-C',repo,'add','README.md']);execFileSync('git',['-C',repo,'commit','--quiet','-m','initial']);
    const workspace=await validateWorkspaceSetup({repoPath:repo,allowedScope:['README.md','src/http/'],validationCommands:[{name:'fixture check',command:'true',args:[]}]});
    const bridge=createServer((req,res)=>{let input='';req.on('data',chunk=>input+=chunk);req.on('end',()=>{res.setHeader('content-type','application/json');if(req.method==='GET'&&req.url==='/v1/uhp'){res.end(JSON.stringify({capabilities:{extensions:{foreman_workspace_bridge_v1:{version:1,seed:true,complete_snapshot:true,execution_boundary:'bubblewrap'}}}}));return;}if(req.method==='POST'&&req.url==='/extensions/foreman-workspace/v1/workspaces'){const request=JSON.parse(input);res.end(JSON.stringify({workspace_id:'task-isolated-workspace',base_commit:request.base_commit}));return;}res.statusCode=404;res.end('{}');});});bridge.listen(0,'127.0.0.1');await once(bridge,'listening');servers.push(bridge);const address=bridge.address() as import('node:net').AddressInfo,bridgeBaseUrl=`http://127.0.0.1:${address.port}`;
    const dirData=join(dir,'data'),store=new JsonStore(join(dirData,'state.json'));let controller:Controller;
    const submissions:any[]=[];const adapter:UhpAdapter={submit:async input=>{submissions.push(input);const text=input.roleId==='orchestrator'?JSON.stringify({workerTask:'Update README.md with a short note.'}):input.roleId==='reviewer'?JSON.stringify({verdict:'recommend',rationale:'Fixture evidence is ready for human review.'}):input.taskId==='project-planner'?JSON.stringify({reply:'I separated the README and endpoint work.',tasks:[{title:'Update README',goal:'Document requested behavior.',suggestedAllowedPaths:['README.md'],validationCriteria:['README check passes']},{title:'Add endpoint',goal:'Implement the API route.',suggestedAllowedPaths:['src/http/'],validationCriteria:['Endpoint tests pass']}]}):'Worker fixture completed';const current=input.roleId==='reviewer'?(await store.load()).projects.flatMap(p=>p.tasks.flatMap(t=>t.runs)).find(run=>run.id===input.runId):undefined;const validation=current?(controller as any).reviewerEvidencePackage(current).controllerValidation:undefined;return {externalId:`opened-${input.roleId}-${submissions.length}`,responseId:`opened-response-${input.roleId}-${submissions.length}`,sessionId:`opened-session-${input.roleId}`,status:'completed',outputText:text,actualModel:'model-fixture',requestedModel:'model-fixture',selectedHarnessId:'fixture',...(input.roleId==='reviewer'?{reviewerExecution:{mode:'read_only',mutationAttempted:false,validation}}:{})};},cancel:async()=>({status:'cancelled'})};
    await store.mutate(state=>{for(const role of state.roles){role.enabled=true;role.availableConfigs=[{harnessId:'fixture',model:'model-fixture'}];role.config={harnessId:'fixture',model:'model-fixture'};}});controller=new Controller(store,adapter);controller.configureVerifiedWorkspace({repoPath:workspace.repoPath,allowedScope:workspace.allowedScope,commands:workspace.validationCommands,bridgeBaseUrl});
    const project:any=await controller.createProject('Opened fixture repository');const planned=await controller.sendProjectPlannerMessage(project.id,'Update the README and add an endpoint.');const [readmeTask]=planned.createdTasks;expect(readmeTask).toBeTruthy();expect(submissions.filter(call=>call.roleId==='worker')).toHaveLength(0);await saveWorkspaceSetup(dirData,project.id,{repoPath:workspace.repoPath,allowedScope:workspace.allowedScope,validationCommands:workspace.validationCommands});const existingProjectId=await findSavedProjectForRepository(dirData,(await store.load()).projects,workspace.repoPath);expect(existingProjectId).toBe(project.id);const restartedState=await new Controller(new JsonStore(store.filePath),adapter).state();expect(restartedState.projects.filter(item=>item.id===existingProjectId)).toHaveLength(1);expect(restartedState.projects.find(item=>item.id===project.id)?.plannerMessages?.map(item=>item.role)).toEqual(['user','planner']);
    (controller as any).verifyWorkerOutput=async(runId:string,workerId:string)=>{let result:any;await store.mutate(state=>{const run=state.projects[0]!.tasks.flatMap(task=>task.runs).find(item=>item.id===runId)!,worker=run.assignments.find(item=>item.id===workerId)!,commands=run.validationCommands!,stamp=new Date().toISOString(),digest=createHash('sha256').update(JSON.stringify(commands.map(command=>({args:command.args,command:command.command,name:command.name})))).digest('hex');run.workerEvidence={provenance:'bridge_snapshot',workerAssignmentId:worker.id,responseId:worker.responseId!,workspaceId:run.workspaceId,pinnedBaseCommit:run.pinnedBaseCommit!,completeSnapshot:{reportedComplete:true,reportedErrors:0,entryCount:1},scopeVerified:true,allowedScope:run.allowedScope!,entries:[],changes:[{path:'README.md',kind:'modify'}],reviewDiff:'diff --git a/README.md b/README.md\n+Fixture note',acceptance:'not_decided'};run.validation={id:'fixture-validation',status:'passed',passed:true,reportedPassed:true,checks:commands.map(command=>({name:command.name,passed:true})),observations:commands.map(command=>({name:command.name,command:command.command,args:command.args,exitCode:0,timedOut:false,output:'passed',outputTruncated:false,startedAt:stamp,finishedAt:stamp,passed:true})),policy:{requireAllChecksPass:true,configuredCheckCount:commands.length,commandDigest:digest},gitEvidence:{status:'verified',commit:run.pinnedBaseCommit!,changedPaths:['README.md'],submittedAt:new Date().toISOString()},createdAt:stamp};run.sessions.orchestrator.uhpSessionId=run.assignments.filter(item=>item.roleId==='orchestrator').at(-1)?.sessionId;run.orchestratorInbox=(controller as any).buildOrchestratorInbox(runId,run);result={workerEvidence:run.workerEvidence,validation:run.validation};});return result;};
    const started=await controller.startTaskWork(readmeTask!.id,{scope:['README.md'],validationCommands:[{name:'task README check',command:'true',args:[]}],budgets:{roleTurns:{planner:1,orchestrator:1,worker:1,reviewer:1},workerAttempts:1}});expect(started.id).toMatch(/^run_/);
    let completed:any;for(let i=0;i<500;i++){const latest=(await store.load()).projects[0]!.tasks.find(task=>task.id===readmeTask!.id)!.runs[0]!;if(latest.controller&&!latest.controller.active){completed=latest;expect(latest.workerEvidence).toMatchObject({workerAssignmentId:expect.any(String),pinnedBaseCommit:workspace.head,allowedScope:['README.md']});expect(latest.validation).toMatchObject({status:'passed',policy:{configuredCheckCount:1},observations:[{name:'task README check',command:'true'}]});expect(latest.orchestratorInbox?.runId).toBe(latest.id);break;}await new Promise(resolve=>setTimeout(resolve,5));if(i===499)throw new Error('The explicitly started task did not finish its simulated run');}
    const saved=(await store.load()).projects[0]!,selected=saved.tasks.find(task=>task.id===readmeTask!.id)!,other=saved.tasks.find(task=>task.id!==readmeTask!.id)!;expect(selected.runs).toHaveLength(1);expect(other.runs).toHaveLength(0);expect(selected.runs[0]!.workspaceId).toBe('task-isolated-workspace');expect(selected.runs[0]!.validationCommands).toEqual([{name:'task README check',command:'true',args:[]}]);const reviewer=completed.assignments.find((assignment:any)=>assignment.roleId==='reviewer');expect(reviewer).toMatchObject({reviewerInboxId:completed.orchestratorInbox.id,reviewerEvidenceDigest:completed.orchestratorInbox.evidenceDigest});expect(submissions.map(call=>call.roleId)).toEqual(['planner','orchestrator','worker','reviewer']);
  });

  it('blocks overlapping work until promotion and requires the current Git base',async()=>{
    const dir=await mkdtemp(join(tmpdir(),'foreman-base-gate-'));dirs.push(dir);const repo=join(dir,'repo');await mkdir(repo);const git=(args:string[])=>execFileSync('git',['-C',repo,...args],{encoding:'utf8'}).trim();
    git(['init','--quiet']);git(['config','user.name','Fixture']);git(['config','user.email','fixture@example.test']);await mkdir(join(repo,'src','http'),{recursive:true});await writeFile(join(repo,'src','http','router.ts'),'export const route = "base";\n');git(['add','.']);git(['commit','--quiet','-m','base']);const base=git(['rev-parse','HEAD']);
    await writeFile(join(repo,'src','http','router.ts'),'export const route = "promoted result";\n');git(['add','.']);git(['commit','--quiet','-m','promoted result']);const promotedCommit=git(['rev-parse','HEAD']);
    await writeFile(join(repo,'README.md'),'Integrated promoted work.\n');git(['add','.']);git(['commit','--quiet','-m','integrate promoted result']);const integratedHead=git(['rev-parse','HEAD']);git(['reset','--hard',base]);
    const store=new JsonStore(join(dir,'state.json'));
    const adapter:UhpAdapter={submit:async input=>({externalId:`${input.roleId}-failed`,responseId:`${input.roleId}-failed-response`,sessionId:`${input.roleId}-failed-session`,status:input.roleId==='orchestrator'?'failed':'completed',outputText:input.roleId==='planner'?'Project guidance is available.':'Fixture stopped before dispatch.'}),cancel:async()=>({status:'cancelled'})};
    await store.mutate(state=>{for(const role of state.roles){role.enabled=true;role.availableConfigs=[{harnessId:'fixture',model:'model-fixture'}];role.config={harnessId:'fixture',model:'model-fixture'};}});
    const controller=new Controller(store,adapter);controller.configureVerifiedWorkspace({repoPath:repo,allowedScope:['src/http/'],commands:[{name:'fixture check',command:'true',args:[]}],bridgeBaseUrl:'http://fixture.invalid'});(controller as any).prepareWorkerWorkspace=async(runId:string,pinnedBase:string)=>store.mutate(state=>{const run=state.projects.flatMap(project=>project.tasks.flatMap(task=>task.runs)).find(item=>item.id===runId)!;run.pinnedBaseCommit=pinnedBase;run.workspaceId=`workspace-${runId}`;});
    const project:any=await controller.createProject('Base gate'),first:any=await controller.createTask(project.id,{title:'First task',goal:'Change the shared endpoint.',suggestedAllowedPaths:['src/http/'],validationCriteria:['Endpoint check passes']}),later:any=await controller.createTask(project.id,{title:'Later task',goal:'Continue the shared endpoint work.',suggestedAllowedPaths:['src/http/'],validationCriteria:['Endpoint tests pass']});await controller.sendProjectPlannerMessage(project.id,'Plan independent, bounded endpoint work.');
    const prior:any=await controller.createRun(first.id);await store.mutate(state=>{const run=state.projects[0]!.tasks[0]!.runs[0]!;run.allowedScope=['src/http/'];run.controller={startedAt:new Date().toISOString(),active:true,phase:'orchestrating',budgets:{roleTurns:{planner:1,orchestrator:1,worker:1,reviewer:1},workerAttempts:1}};});
    await expect(controller.startTaskWork(later.id,{scope:['src/http/']})).rejects.toThrow(/active|unpromoted/);expect((await store.load()).projects[0]!.tasks[1]!.runs).toHaveLength(0);
    await store.mutate(state=>{const run=state.projects[0]!.tasks[0]!.runs[0]!;run.controller!.active=false;run.workerEvidence={provenance:'bridge_snapshot',workerAssignmentId:'old-worker',responseId:'old-response',pinnedBaseCommit:base,completeSnapshot:{reportedComplete:true,reportedErrors:0,entryCount:0},scopeVerified:true,allowedScope:['src/http/'],entries:[],changes:[],reviewDiff:'',acceptance:'not_decided'};});
    await expect(controller.startTaskWork(later.id,{scope:['src/http/']})).rejects.toThrow(/active|unpromoted/);expect((await store.load()).projects[0]!.tasks[1]!.runs).toHaveLength(0);
    await store.mutate(state=>{state.projects[0]!.tasks[0]!.runs[0]!.promotion={status:'applied',resultCommit:promotedCommit,updatedAt:new Date().toISOString()};});
    await expect(controller.startTaskWork(later.id,{scope:['src/http/']})).rejects.toThrow(/not integrated into repository HEAD/);expect((await store.load()).projects[0]!.tasks[1]!.runs).toHaveLength(0);
    expect((await store.load()).projects[0]!.tasks[0]!.runs[0]!.promotion?.resultCommit).toBe(promotedCommit);
    await expect(controller.startTaskWork(later.id,{scope:['src/http/'],baseCommit:base})).rejects.toThrow(/not integrated into repository HEAD/);
    await expect(controller.startTaskWork(later.id,{scope:['src/http/'],baseCommit:promotedCommit})).rejects.toThrow(`Selected Git base is stale; current repository HEAD is ${base}`);
    git(['reset','--hard',integratedHead]);expect(git(['rev-parse','HEAD'])).toBe(integratedHead);
    const started=await controller.startTaskWork(later.id,{scope:['src/http/'],budgets:{roleTurns:{planner:1,orchestrator:1,worker:1,reviewer:1},workerAttempts:1}});expect(started.pinnedBaseCommit).toBe(integratedHead);expect(started.workspaceId).toContain(started.id);expect((await store.load()).projects[0]!.tasks[1]!.runs).toHaveLength(1);expect(prior.id).not.toBe(started.id);for(let i=0;i<100;i++){const latest=(await store.load()).projects[0]!.tasks[1]!.runs[0]!;if(!latest.controller?.active)break;await new Promise(resolve=>setTimeout(resolve,5));if(i===99)throw new Error('Fixture Orchestrator did not reach its expected failed terminal state');}
  });

  it('blocks a same-task Start while prior evidence awaits approval, then requires promoted work in current HEAD',async()=>{
    const dir=await mkdtemp(join(tmpdir(),'foreman-same-task-start-'));dirs.push(dir);const repo=join(dir,'repo');await mkdir(repo);const git=(args:string[])=>execFileSync('git',['-C',repo,...args],{encoding:'utf8'}).trim();
    git(['init','--quiet']);git(['config','user.name','Fixture']);git(['config','user.email','fixture@example.test']);await mkdir(join(repo,'src','http'),{recursive:true});await writeFile(join(repo,'src','http','router.ts'),'export const route = "base";\n');git(['add','.']);git(['commit','--quiet','-m','base']);const base=git(['rev-parse','HEAD']);
    await writeFile(join(repo,'src','http','router.ts'),'export const route = "approved work";\n');git(['add','.']);git(['commit','--quiet','-m','promoted result']);const resultCommit=git(['rev-parse','HEAD']);
    await writeFile(join(repo,'README.md'),'Promoted result integrated.\n');git(['add','.']);git(['commit','--quiet','-m','integrate promoted result']);const currentHead=git(['rev-parse','HEAD']);git(['reset','--hard',base]);
    const store=new JsonStore(join(dir,'state.json')),submissions:any[]=[];const adapter:UhpAdapter={submit:async input=>{submissions.push(input);return {externalId:`same-${input.roleId}-${submissions.length}`,responseId:`same-response-${input.roleId}-${submissions.length}`,sessionId:`same-session-${input.roleId}`,status:input.roleId==='orchestrator'?'failed':'completed',outputText:input.roleId==='planner'?'Plan saved for this task.':'Fixture stopped before Worker dispatch.'};},cancel:async()=>({status:'cancelled'})};
    await store.mutate(state=>{for(const role of state.roles){role.enabled=true;role.availableConfigs=[{harnessId:'fixture',model:'model-fixture'}];role.config={harnessId:'fixture',model:'model-fixture'};}});
    const controller=new Controller(store,adapter);controller.configureVerifiedWorkspace({repoPath:repo,allowedScope:['src/http/','README.md'],commands:[{name:'fixture check',command:'true',args:[]}],bridgeBaseUrl:'http://fixture.invalid'});(controller as any).prepareWorkerWorkspace=async(runId:string,pinnedBase:string)=>store.mutate(state=>{const run=state.projects.flatMap(project=>project.tasks.flatMap(task=>task.runs)).find(item=>item.id===runId)!;run.pinnedBaseCommit=pinnedBase;run.workspaceId=`workspace-${runId}`;});
    const project:any=await controller.createProject('Same task retry'),task:any=await controller.createTask(project.id,{title:'Shared endpoint task',goal:'Change the endpoint safely.',suggestedAllowedPaths:['src/http/'],validationCriteria:['Endpoint check passes']}),failedTask:any=await controller.createTask(project.id,{title:'Retry failed run',goal:'Retry after a terminal failure with no evidence.',suggestedAllowedPaths:['README.md'],validationCriteria:['README check passes']});await controller.sendProjectPlannerMessage(project.id,'Prepare the bounded endpoint task.');
    const previous:any=await controller.createRun(task.id);await store.mutate(state=>{const run=state.projects[0]!.tasks[0]!.runs[0]!;run.status='review';run.allowedScope=['src/http/'];run.controller={startedAt:new Date().toISOString(),active:false,phase:'awaiting_approval',budgets:{roleTurns:{planner:1,orchestrator:1,worker:1,reviewer:1},workerAttempts:1}};run.workerEvidence={provenance:'bridge_snapshot',workerAssignmentId:'prior-worker',responseId:'prior-response',pinnedBaseCommit:base,completeSnapshot:{reportedComplete:true,reportedErrors:0,entryCount:1},scopeVerified:true,allowedScope:['src/http/'],entries:[],changes:[{path:'src/http/router.ts',kind:'modify'}],reviewDiff:'verified prior diff',acceptance:'not_decided'};});
    const failedPrior:any=await controller.createRun(failedTask.id);await store.mutate(state=>{const run=state.projects[0]!.tasks[1]!.runs[0]!;run.status='failed';run.controller={startedAt:new Date().toISOString(),active:false,phase:'stopped',budgets:{roleTurns:{planner:1,orchestrator:1,worker:1,reviewer:1},workerAttempts:1}};});
    const startOptions={scope:['src/http/'],validationCommands:[{name:'task check',command:'true',args:[]}],budgets:{roleTurns:{planner:1 as const,orchestrator:1 as const,worker:1 as const,reviewer:1 as const},workerAttempts:1}};
    const retry=await controller.startTaskWork(failedTask.id,{...startOptions,scope:['README.md']});expect(retry.id).not.toBe(failedPrior.id);expect((await store.load()).projects[0]!.tasks[1]!.runs).toHaveLength(2);for(let i=0;i<100;i++){const latest=(await store.load()).projects[0]!.tasks[1]!.runs[1]!;if(!latest.controller?.active)break;await new Promise(resolve=>setTimeout(resolve,5));if(i===99)throw new Error('Failed no-evidence retry did not reach its terminal state');}expect(submissions.some(call=>call.roleId==='worker')).toBe(false);
    const callsBeforeBlockedStart=submissions.length;await expect(controller.startTaskWork(task.id,startOptions)).rejects.toThrow(/approval|unpromoted|prior run/i);expect((await store.load()).projects[0]!.tasks[0]!.runs).toHaveLength(1);expect(submissions).toHaveLength(callsBeforeBlockedStart);expect(submissions.some(call=>call.roleId==='worker')).toBe(false);
    await store.mutate(state=>{const run=state.projects[0]!.tasks[0]!.runs[0]!;run.approval={id:'prior-approval',approved:true,decision:'approved',evidenceCommit:base,evidenceDigest:'prior-evidence',rationale:'Approved fixture evidence',createdAt:new Date().toISOString()};run.promotion={status:'applied',resultCommit,updatedAt:new Date().toISOString()};state.projects[0]!.tasks[0]!.status='completed';});
    await expect(controller.startTaskWork(task.id,startOptions)).rejects.toThrow(/not integrated into repository HEAD/);expect((await store.load()).projects[0]!.tasks[0]!.runs).toHaveLength(1);expect(submissions.length).toBe(callsBeforeBlockedStart);
    git(['reset','--hard',currentHead]);const started=await controller.startTaskWork(task.id,startOptions);expect(started.id).not.toBe(previous.id);expect(started.pinnedBaseCommit).toBe(currentHead);expect(started.workspaceId).toContain(started.id);expect((await store.load()).projects[0]!.tasks[0]!.runs).toHaveLength(2);
    for(let i=0;i<100;i++){const latest=(await store.load()).projects[0]!.tasks[0]!.runs[1]!;if(!latest.controller?.active)break;await new Promise(resolve=>setTimeout(resolve,5));if(i===99)throw new Error('Fixture Orchestrator did not reach its expected failed terminal state');}expect(submissions.some(call=>call.roleId==='worker')).toBe(false);
  });
});
