import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { describe, expect, it } from 'vitest';
import { App, type State, type TaskStartPreview } from '../ui/main.js';

describe('project Planner UI',()=>{
  it('shows the continuing Planner, task tree, start controls, and named navigation with inline icons',()=>{
    const state:State={projects:[{id:'prj_fixture',name:'Opened repository',plannerSession:{localId:'planner-session-fixture',roleId:'planner',generation:1,status:'active',config:{harnessId:'fixture',model:'simulated'},startedAt:'2026-01-01T00:00:00.000Z'},plannerMessages:[{id:'pmsg_user',role:'user',text:'Update the node README and add a REST endpoint.',createdAt:'2026-01-01T00:00:00.000Z'},{id:'pmsg_planner',role:'planner',text:'I split this into two tasks.',createdAt:'2026-01-01T00:01:00.000Z'}],tasks:[{id:'tsk_readme_fixture',title:'Update README',goal:'Document the node behavior.',suggestedAllowedPaths:['README.md'],validationCriteria:['README check passes'],status:'ready',runs:[]},{id:'tsk_endpoint_fixture',title:'Add REST endpoint',goal:'Implement the requested API endpoint.',suggestedAllowedPaths:['src/http/'],validationCriteria:['Endpoint tests pass'],status:'ready',runs:[]}]}],roles:[...['planner','orchestrator','worker','reviewer'].map(id=>({id,name:id,enabled:true,config:{harnessId:'fixture',model:'simulated'},availableConfigs:[{harnessId:'fixture',model:'simulated'}]}))]};
    const html=renderToStaticMarkup(createElement(App,{initialState:state}));
    expect(html).toContain('Talk to the Planner');expect(html).toContain('One continuing conversation for this repository');expect(html).toContain('Update the node README and add a REST endpoint.');expect(html).toContain('Update README');expect(html).toContain('Add REST endpoint');expect(html).toContain('Start work');expect(html).toContain('Message project Planner');
    expect(html).not.toContain('aria-label="Main navigation"');expect(html).toContain('Project tree');expect(html).toContain('class="node project selected" title="Opened repository"');expect(html).toContain('class="node task selected" title="Update README"');
    expect(html).toContain('aria-label="Refresh state"');expect(html).toContain('<svg aria-hidden="true" focusable="false"');expect(html).not.toContain('objtext');
  });
  it('hides a legacy structured proposal payload and keeps the readable Planner reply',()=>{
    const state:State={projects:[{id:'prj_fixture',name:'Opened repository',plannerAssignments:[{id:'asgn_fixture',roleId:'planner',status:'succeeded',result:{reply:'See [the docs](https://example.com/docs) for context.',tasks:[{title:'Add health endpoint'}]}}],plannerMessages:[{id:'pmsg_user',role:'user',text:'Add a health endpoint.',createdAt:'2026-01-01T00:00:00.000Z'},{id:'pmsg_planner',role:'planner',assignmentId:'asgn_fixture',text:'I prepared a task.',createdAt:'2026-01-01T00:01:00.000Z'}],tasks:[]}],roles:[]};
    const html=renderToStaticMarkup(createElement(App,{initialState:state}));
    expect(html).toContain('I prepared a task.');expect(html).not.toContain('See ');expect(html).not.toContain('href="https://example.com/docs"');expect(html).toContain('Saved Planner proposal · 1 task');expect(html).toContain('Create proposed tasks');expect(html).not.toContain('&quot;tasks&quot;');expect(html).toContain('Message project Planner');
  });
  it('offers recovery from saved task JSON when the Planner message only contains friendly text',()=>{
    const assignmentId='asgn_f32a6c25-24c0-4a22-bc4a-fd536b14fa3f';
    const proposals=[{title:'Add roster import',goal:'Import roster updates.',validationCriteria:['Import validation passes']},{title:'Add profile sync',goal:'Sync player profiles.',validationCriteria:['Sync test passes']},{title:'Document import',goal:'Document roster import.',validationCriteria:['Docs build passes']}];
    const state:State={projects:[{id:'prj_saved_proposal',name:'Saved proposal',plannerAssignments:[{id:assignmentId,roleId:'planner',status:'succeeded',result:JSON.stringify({reply:'I split the request into three tasks.',tasks:proposals})}],plannerMessages:[{id:'pmsg_planner',role:'planner',assignmentId,text:'I split the request into three tasks.',createdAt:'2026-09-23T12:00:00.000Z'}],tasks:[]}],roles:[]};
    const html=renderToStaticMarkup(createElement(App,{initialState:state}));
    expect(html).toContain('I split the request into three tasks.');expect(html).toContain('Saved Planner proposal · 3 tasks');expect(html).toContain('Create proposed tasks');expect(html).not.toContain('Add roster import');expect(html).not.toContain('"tasks"');
  });
  it('does not offer proposal recovery for a completed conversational Planner reply',()=>{
    const state:State={projects:[{id:'prj_conversation',name:'Conversation only',plannerAssignments:[{id:'asgn_chat',roleId:'planner',status:'succeeded',result:'I can help with that. What should happen when the endpoint receives an empty query?'}],plannerMessages:[{id:'pmsg_chat',role:'planner',assignmentId:'asgn_chat',text:'I can help with that. What should happen when the endpoint receives an empty query?',createdAt:'2026-09-23T12:00:00.000Z'}],tasks:[]}],roles:[]};
    const html=renderToStaticMarkup(createElement(App,{initialState:state}));
    expect(html).toContain('What should happen when the endpoint receives an empty query?');expect(html).not.toContain('Create proposed tasks');expect(html).not.toContain('Saved Planner proposal');
  });
  it('puts task plan approval first and keeps run settings collapsed under Advanced options',()=>{
    const state:State={projects:[{id:'prj_review',name:'Review project',tasks:[{id:'tsk_review',title:'Add search endpoint',goal:'Let clients search active records.',validationCriteria:['Returns matching records','Rejects invalid query'],suggestedAllowedPaths:['src/search/'],status:'ready'}]}],roles:['orchestrator','worker','reviewer'].map(id=>({id,name:id,enabled:true,config:{harnessId:'local',model:'safe-model'},availableConfigs:[{harnessId:'local',model:'safe-model'}]}))};
    const preview:TaskStartPreview={taskId:'tsk_review',scope:['src/search/'],roleConfigs:Object.fromEntries(['orchestrator','worker','reviewer'].map(id=>[id,{harnessId:'local',model:'safe-model'}])),validationCriteria:['Returns matching records','Rejects invalid query'],validationCommands:[{name:'Tests',command:'pnpm',args:['test']}],budgets:{roleTurns:{planner:3,orchestrator:2,worker:1,reviewer:1},workerAttempts:1},baseCommit:'a'.repeat(40),requiresExplicitBase:false,reasons:[],canStart:true};
    const html=renderToStaticMarkup(createElement(App,{initialState:state,initialTaskStartPreview:preview}));
    expect(html).toContain('Add search endpoint');expect(html).toContain('Let clients search active records.');expect(html).toContain('Returns matching records');expect(html).toContain('Rejects invalid query');expect(html).toContain('Approve task &amp; start work');expect(html).toContain('TASK PLAN APPROVAL');expect(html).toContain('Result approval remains a separate decision.');expect(html).toContain('Advanced options');expect(html).toContain('<details class="task-advanced">');expect(html).not.toContain('Start work</button>');
  });
  it('surfaces preview blockers in task review and prevents task plan approval',()=>{
    const state:State={projects:[{id:'prj_blocked',name:'Blocked project',tasks:[{id:'tsk_blocked',title:'Update report',goal:'Update the report.',validationCriteria:['Report lint passes'],status:'ready'}]}],roles:[]};
    const preview:TaskStartPreview={taskId:'tsk_blocked',scope:[],roleConfigs:{},validationCriteria:['Report lint passes'],validationCommands:[],requiresExplicitBase:true,reasons:['Choose at least one allowed path before starting this task','Dependency tsk_prior must be completed and promoted'],dependencyTaskIds:['tsk_prior'],canStart:false};
    const html=renderToStaticMarkup(createElement(App,{initialState:state,initialTaskStartPreview:preview}));
    expect(html).toContain('Resolve these blockers before starting');expect(html).toContain('Choose at least one allowed path before starting this task');expect(html).toContain('Dependency tsk_prior must be completed and promoted');expect(html).toContain('Related work must be integrated first');expect(html).toContain('pins the updated current HEAD automatically');expect(html).toContain('Approve task &amp; start work');expect(html).toMatch(/<button class="primary task-approve-button" disabled="">Approve task &amp; start work<\/button>/);
  });
  it('shows a persisted task plan approval separately from later result approval',()=>{
    const state:State={projects:[{id:'prj_approved',name:'Approved project',tasks:[{id:'tsk_approved',title:'Document API',goal:'Document the API.',validationCriteria:['Docs build passes'],status:'in progress',planApproval:{status:'approved',approvedAt:'2026-01-02T00:00:00.000Z',specDigest:'digest',runId:'run_approved'},runs:[]}]}],roles:[]};
    const html=renderToStaticMarkup(createElement(App,{initialState:state}));
    expect(html).toContain('Task plan approved');expect(html).toContain('<summary>Run ID</summary><code>run_approved</code>');expect(html).toContain('Result review and approval are still separate.');
  });
  it('keeps Planner first and shows a stopped validation phase with selectable role evidence',()=>{
    const state:State={projects:[{id:'prj_workflow',name:'Workflow project',plannerMessages:[{id:'pmsg_workflow',role:'user',text:'Add the roster import endpoint.',createdAt:'2026-09-24T12:00:00.000Z'}],tasks:[{id:'tsk_workflow',title:'Add roster import',goal:'Accept roster updates.',validationCriteria:['Import tests pass'],suggestedAllowedPaths:['src/import/'],status:'in progress',runs:[{id:'run_workflow',status:'failed',controller:{startedAt:'2026-09-24T12:01:00.000Z',phase:'stopped',stoppedReason:'Controller validation evidence exceeds the 16,000 byte inbox limit',active:false},assignments:[{id:'asgn_orchestrator',roleId:'orchestrator',status:'succeeded',result:'Worker result was ready for validation.'},{id:'asgn_worker',roleId:'worker',status:'succeeded',result:'Implemented roster import endpoint.'}],workerEvidence:{workerAssignmentId:'asgn_worker',responseId:'resp_worker',pinnedBaseCommit:'a'.repeat(40),completeSnapshot:{reportedComplete:true,reportedErrors:0,entryCount:1},scopeVerified:true,allowedScope:['src/import/'],entries:[{path:'src/import/index.ts',kind:'file'}],changes:[{path:'src/import/index.ts',kind:'added',summary:'Adds the endpoint'}]},rejectedWorkerAttempts:[{id:'rejected_worker_snapshot',proposal:{id:'proposal_worker',status:'dispatched',text:'Implement the roster import endpoint.',orchestratorAssignmentId:'asgn_orchestrator',createdAt:'2026-09-24T12:02:00.000Z'},workerAssignmentId:'asgn_worker',reason:'An earlier reconciliation rejected this snapshot.',evidenceStatus:'rejected_untrusted',createdAt:'2026-09-24T12:03:00.000Z'}]}]}]}],roles:[...['planner','orchestrator','worker','reviewer'].map(id=>({id,name:id,enabled:true,config:{harnessId:'fixture',model:'simulated'},availableConfigs:[{harnessId:'fixture',model:'simulated'}]}))],events:[{id:'evt_worker_verified',type:'worker.evidence_verified',entityType:'run',entityId:'run_workflow',at:'2026-09-24T12:03:00.000Z',data:{workerAssignmentId:'asgn_worker',scopeVerified:true}},{id:'evt_worker_evidence_rejected',type:'worker.evidence_rejected',entityType:'run',entityId:'run_workflow',at:'2026-09-24T12:03:30.000Z',data:{workerAssignmentId:'asgn_worker',error:'Inbox too large'}},{id:'evt_worker_attempt_rejected',type:'worker.attempt_rejected',entityType:'run',entityId:'run_workflow',at:'2026-09-24T12:03:40.000Z',data:{workerAssignmentId:'asgn_worker',reason:'Snapshot previously rejected'}},{id:'evt_validation_stop',type:'controller.phase_changed',entityType:'run',entityId:'run_workflow',at:'2026-09-24T12:04:00.000Z',data:{phase:'validating'}}]};
    const html=renderToStaticMarkup(createElement(App,{initialState:state}));
    const plannerIndex=html.indexOf('Talk to the Planner');
    const phasesIndex=html.indexOf('Run phase progress');
    expect(plannerIndex).toBeGreaterThanOrEqual(0);expect(phasesIndex).toBeGreaterThan(plannerIndex);
    expect(html).toContain('Validation blocked');expect(html).toContain('Controller validation evidence exceeds the 16,000 byte inbox limit');
    expect(html).toContain('Select workflow role');expect(html).toContain('aria-pressed="true"');
    expect(html).toContain('phase-step done');expect(html).toContain('phase-step blocked');expect(html).toContain('phase-step waiting');
    expect(html).toContain('aria-label="Run phase progress"');
    expect(html).toMatch(/class="phase-step done[^\"]*"[^>]*><button[^>]*aria-label="Orchestrator phase, Done/);
    expect(html).toMatch(/class="phase-step done[^\"]*"[^>]*><button[^>]*aria-label="Verify phase, Done/);
    expect(html).toMatch(/class="phase-step blocked[^\"]*"[^>]*><button[^>]*aria-label="Validate phase, Blocked/);
    expect(html).toContain('aria-label="Validate phase, Blocked. Select for activity and evidence"');
    expect(html).toContain('aria-label="Reviewer phase, Waiting. Select for activity and evidence"');
    expect(html).toContain('Orchestrator activity and evidence');
    expect(html).toContain('aria-label="Worker, status Succeeded. Select for details"');
    expect(html).toContain('aria-label="Reviewer, status Unknown. Select for details"');
    expect(html).not.toContain('Reviewer complete');expect(html).not.toContain('Reviewer activity and evidence');
    expect(html).not.toContain('Foreman rejected this snapshot as untrusted');
    expect(html).toContain('Complete snapshot verified · 1 entries · Scope verified');
    expect(html).toContain('>History</button>');expect(html).not.toContain('Historical rejection superseded by verified evidence');expect(html).not.toContain('Worker assignment asgn_worker');
    expect(html).not.toContain('Worker Attempt Rejected');expect(html).not.toContain('Worker Evidence Rejected');
    expect(html).toContain('This run has verified Worker evidence');expect(html).toContain('Resolve its review, human decision, or promotion before starting another run');expect(html).toContain('Go to Evidence &amp; approval');expect(html).not.toContain('Approve task &amp; start work');
  });
  it('keeps the run view concise by default while leaving approval and details reachable',()=>{
    const longDiff='+++ b/src/endpoint.ts\n'+('line with implementation detail\n'.repeat(80));
    const state:State={projects:[{id:'prj_compact',name:'Compact project',plannerMessages:[{id:'pmsg_compact',role:'user',text:'Add the endpoint.',createdAt:'2026-09-24T12:00:00.000Z'}],tasks:[{id:'tsk_private_long_identifier',title:'Add endpoint',goal:'Accept roster updates.',validationCriteria:['Import tests pass'],suggestedAllowedPaths:['src/import/'],status:'in progress',runs:[{id:'run_private_long_identifier',status:'review',controller:{startedAt:'2026-09-24T12:01:00.000Z',phase:'stopped',active:false},assignments:[{id:'asgn_orchestrator_private',roleId:'orchestrator',status:'succeeded'},{id:'asgn_worker_private',roleId:'worker',status:'succeeded'},{id:'asgn_reviewer_private',roleId:'reviewer',status:'failed',error:'Reviewer submission returned HTTP 400'}],workerEvidence:{workerAssignmentId:'asgn_worker_private',responseId:'resp_worker_private',pinnedBaseCommit:'a'.repeat(40),completeSnapshot:{reportedComplete:true,reportedErrors:0,entryCount:1},scopeVerified:true,allowedScope:['src/import/'],entries:[{path:'src/import/index.ts',kind:'file'}],changes:[{path:'src/import/index.ts',kind:'added',summary:'Adds the endpoint'}],reviewDiff:longDiff},validation:{status:'passed',observations:[{name:'Import tests',command:'pnpm',args:['test'],exitCode:0,signal:null,timedOut:false,output:'passed',outputTruncated:false,passed:true}]}}]}]}],roles:[...['planner','orchestrator','worker','reviewer'].map(id=>({id,name:id,enabled:true,config:{harnessId:'fixture',model:'simulated'},availableConfigs:[{harnessId:'fixture',model:'simulated'}]}))]};
    const preview:TaskStartPreview={taskId:'tsk_private_long_identifier',scope:['src/import/'],roleConfigs:Object.fromEntries(['orchestrator','worker','reviewer'].map(id=>[id,{harnessId:'fixture',model:'simulated'}])),validationCriteria:['Import tests pass'],validationCommands:[{name:'Tests',command:'pnpm',args:['test']}],budgets:{roleTurns:{planner:3,orchestrator:2,worker:1,reviewer:1},workerAttempts:1},baseCommit:'a'.repeat(40),requiresExplicitBase:false,reasons:[],canStart:true};
    const html=renderToStaticMarkup(createElement(App,{initialState:state,initialTaskStartPreview:preview}));
    const plannerIndex=html.indexOf('Talk to the Planner');const workflowIndex=html.indexOf('Run phase progress');const taskReviewIndex=html.indexOf('TASK REVIEW');
    expect(plannerIndex).toBeGreaterThanOrEqual(0);expect(workflowIndex).toBeGreaterThan(plannerIndex);expect(taskReviewIndex).toBeGreaterThan(workflowIndex);
    expect(html).toContain('<details class="workflow-more"><summary>Details</summary>');expect(html).toContain('<details class="run-meta-disclosure"><summary>Session and usage details</summary>');
    expect(html).toContain('<details class="evidence-block diff-block">');expect(html).not.toContain('<details class="evidence-block diff-block" open');expect(html).not.toContain('<details class="workflow-more" open');
    expect(html).toContain('This run has verified Worker evidence');expect(html).toContain('Go to Reviewer retry');expect(html).not.toContain('Go to Evidence &amp; approval');expect(html).not.toContain('Approve task &amp; start work');expect(html).toContain('Reviewer phase, Blocked. Select for activity and evidence');expect(html).toContain(longDiff);
  });
  it('keeps run selection explicit and makes durable history easy to reach',()=>{
    const state:State={projects:[{id:'prj_latest_run',name:'Latest run project',tasks:[{id:'tsk_latest_run',title:'Add endpoint',goal:'Add the endpoint.',status:'failed',runs:[
      {id:'run_old_failed',status:'failed',controller:{startedAt:'2026-09-24T11:00:00.000Z',phase:'stopped',active:false},assignments:[{id:'asgn_old_worker',roleId:'worker',status:'failed'}]},
      {id:'run_latest_failed',status:'failed',controller:{startedAt:'2026-09-24T12:00:00.000Z',phase:'stopped',stoppedReason:'Reviewer submission returned HTTP 400: review_evidence_invalid',active:false},assignments:[{id:'asgn_latest_worker',roleId:'worker',status:'succeeded'},{id:'asgn_latest_reviewer',roleId:'reviewer',status:'failed',error:'Reviewer submission returned HTTP 400: review_evidence_invalid'}],workerEvidence:{workerAssignmentId:'asgn_latest_worker',responseId:'resp_latest_worker',pinnedBaseCommit:'a'.repeat(40),completeSnapshot:{reportedComplete:true,reportedErrors:0,entryCount:1},scopeVerified:true,allowedScope:['src/'],entries:[],changes:[],reviewDiff:'verified diff'},validation:{status:'passed',observations:[{name:'Tests',command:'pnpm',args:['test'],exitCode:0,timedOut:false,output:'passed',outputTruncated:false,passed:true}]}}
    ]}]}],roles:[...['orchestrator','worker','reviewer'].map(id=>({id,name:id,enabled:true,config:{harnessId:'fixture',model:'simulated'},availableConfigs:[{harnessId:'fixture',model:'simulated'}]}))]};
    const html=renderToStaticMarkup(createElement(App,{initialState:state}));
    expect(html).toContain('>History</button>');expect(html).toContain('>Usage</button>');expect(html).toContain('class="node run');
    expect(html).not.toContain('<div class="detail-row"><span>Run ID</span><code>run_latest_failed</code></div>');
    expect(html).toContain('Go to Reviewer retry');
    const recovered=structuredClone(state),recoveredRun=recovered.projects[0]!.tasks[0]!.runs![1]!;recoveredRun.status='review';recoveredRun.assignments![1]!.status='succeeded';delete recoveredRun.assignments![1]!.error;
    const recoveredHtml=renderToStaticMarkup(createElement(App,{initialState:recovered}));expect(recoveredHtml).not.toContain('Reviewer submission returned HTTP 400: review_evidence_invalid');
  });
  it('shows restored Reviewer evidence and human decision controls after prompt-limit recovery only in awaiting approval',()=>{
    const recommendation={id:'rec_recovered',status:'proposed' as const,provenance:'uhp_response' as const,reviewerAssignmentId:'asgn_recovered_reviewer',harnessId:'fixture',model:'model-fixture',responseId:'resp_recovered_reviewer',sessionId:'session_recovered_reviewer',reviewMode:'read_only' as const,mutationAttempted:false as const,verdict:'request_changes' as const,rationale:'The verified change needs one adjustment.',createdAt:'2026-09-25T12:00:00.000Z'};
    const state:State={projects:[{id:'prj_recovered',name:'Recovered project',tasks:[{id:'tsk_recovered',title:'Recovered task',status:'in progress',runs:[{id:'run_recovered',status:'awaiting_approval',controller:{startedAt:'2026-09-25T11:00:00.000Z',phase:'stopped',stoppedReason:'UHP request failed (400): prompt_limit',active:false,budgets:{roleTurns:{planner:2,orchestrator:3,worker:2,reviewer:2},workerAttempts:2}},reviewerRecommendation:recommendation,assignments:[{id:'asgn_recovered_worker',roleId:'worker',status:'succeeded',responseId:'resp_recovered_worker',sessionId:'session_recovered_worker'},{id:'asgn_recovered_reviewer',roleId:'reviewer',status:'succeeded',responseId:recommendation.responseId,sessionId:recommendation.sessionId,requestedConfig:{harnessId:'fixture',model:'model-fixture'}},{id:'asgn_recovered_orchestrator',roleId:'orchestrator',status:'failed',error:'UHP request failed (400): prompt_limit',requestedConfig:{harnessId:'fixture',model:'model-fixture'}}],workerEvidence:{workerAssignmentId:'asgn_recovered_worker',responseId:'resp_recovered_worker',pinnedBaseCommit:'a'.repeat(40),completeSnapshot:{reportedComplete:true,reportedErrors:0,entryCount:1},scopeVerified:true,allowedScope:['README.md'],entries:[],changes:[{path:'README.md',kind:'modified',summary:'Verified README update'}],reviewDiff:'verified diff',acceptance:'not_decided'},validation:{status:'passed',passed:true,observations:[{name:'Fixture check',command:'true',args:[],exitCode:0,timedOut:false,output:'passed',outputTruncated:false,passed:true}]}}]}]}],roles:[...['orchestrator','worker','reviewer'].map(id=>({id,name:id,enabled:true,config:{harnessId:'fixture',model:'model-fixture'},availableConfigs:[{harnessId:'fixture',model:'model-fixture'}]}))]};
    const html=renderToStaticMarkup(createElement(App,{initialState:state}));
    expect(html).toContain('Recovered for human review');expect(html).toContain('UHP request failed (400): prompt_limit');expect(html).toContain('Awaiting explicit human approval or rejection');expect(html).toContain('>Reject result</button>');expect(html).toContain('>Approve result</button>');expect(html).toContain('Resume Reviewer correction');expect(html).toContain('Resume will make one bounded Orchestrator correction plan, dispatch a Worker retry, run configured local validation, and request a fresh read-only Reviewer response.');expect(html).toContain('This does not approve or promote the result.');
    const exhausted=structuredClone(state);exhausted.projects[0]!.tasks[0]!.runs![0]!.controller!.budgets!.roleTurns.orchestrator=1;
    const exhaustedHtml=renderToStaticMarkup(createElement(App,{initialState:exhausted}));expect(exhaustedHtml).not.toContain('Resume Reviewer correction');expect(exhaustedHtml).toContain('Correction cannot resume: Orchestrator role-turn budget is exhausted.');
    const stale=structuredClone(state);stale.projects[0]!.tasks[0]!.runs![0]!.status='review';
    const staleHtml=renderToStaticMarkup(createElement(App,{initialState:stale}));expect(staleHtml).not.toContain('Recovered for human review');expect(staleHtml).not.toContain('UHP request failed (400): prompt_limit');
  });
  it('keeps project identity and repository switching in the compact header without a duplicate workspace card',()=>{
    const state:State={projects:[{id:'prj_scope',name:'Scope project',repoPath:'/repo/scope-project',tasks:[{id:'tsk_scope',title:'Add endpoint',goal:'Add the requested endpoint.',status:'ready'}]}],roles:[]};
    const workspace={repoPath:'/repo/scope-project',head:'a'.repeat(40),dirty:false,allowedScope:['nodes/','README.md'],validationCommands:[]};
    const html=renderToStaticMarkup(createElement(App,{initialState:state,initialWorkspaceSetup:workspace}));
    expect(html).toContain('class="project-context" aria-label="Current project"');expect(html).toContain('class="project-name" title="Scope project">Scope project</span>');expect(html).toContain('/repo/scope-project');expect(html).toContain('Switch repo');
    expect(html).toContain('<summary>Repository details</summary>');expect(html).not.toContain('ACTIVE REPOSITORY');expect(html).not.toContain('class="repo-summary"');
    expect(html).not.toContain('class="rail"');expect(html).toContain('Project tree');expect(html).toContain('Add endpoint');expect(html).toContain('Add task');expect(html).toContain('Talk to the Planner');
  });
  it('offers per-project Reset Planner and deletion from row menus behind confirmation',()=>{
    const state:State={projects:[{id:'prj_admin',name:'Admin project',plannerMessages:[{id:'pmsg_admin',role:'user',text:'Keep the Planner history.',createdAt:'2026-09-24T12:00:00.000Z'}],tasks:[{id:'tsk_admin',title:'Admin task',goal:'Inspect task actions.',status:'ready'}]},{id:'prj_other_admin',name:'Other admin project',tasks:[]}],roles:[]};
    const html=renderToStaticMarkup(createElement(App,{initialState:state}));
    expect(html).not.toContain('class="rail"');expect(html).toContain('Project tree');expect(html).toContain('class="node project selected" title="Admin project"');expect(html).toContain('class="node task selected" title="Admin task"');expect(html).toContain('title="Other admin project"');
    expect(html).not.toContain('project-settings');expect(html).toContain('class="outline small" type="button"');expect(html).toContain('Reset Planner conversation');expect(html).toContain('Delete project');
    expect(html).toContain('aria-label="Actions for project Admin project"');expect(html).toContain('aria-label="Reset Planner conversation for Admin project"');expect(html).toContain('aria-label="Delete project Admin project"');expect(html).toContain('aria-label="Actions for project Other admin project"');expect(html).toContain('aria-label="Reset Planner conversation for Other admin project"');expect(html.match(/aria-label="Actions for project /g)).toHaveLength(2);
    expect(html).toContain('aria-label="Actions for task Admin task"');
    expect(html).not.toContain('class="admin-confirm"');expect(html).not.toContain('aria-labelledby="admin-action-title"');
  });
  it('offers task row actions without sending a request before confirmation',()=>{
    const state:State={projects:[{id:'prj_task_actions',name:'Task actions project',tasks:[{id:'tsk_approved_actions',title:'Approved task',goal:'Reset or delete this task.',status:'ready',planApproval:{status:'approved',approvedAt:'2026-09-24T12:00:00.000Z',specDigest:'fixture-digest'}}]}],roles:[]};
    const html=renderToStaticMarkup(createElement(App,{initialState:state}));
    expect(html).toContain('class="task-actions"><summary>Task actions</summary>');expect(html).not.toContain('<details class="task-actions" open');
    expect(html).toContain('Reset approved plan');expect(html).toContain('Delete task');expect(html).toContain('danger-action');
    expect(html).toContain('aria-label="Actions for task Approved task"');
    expect(html).not.toContain('class="admin-confirm"');expect(html).not.toContain('aria-labelledby="admin-action-title"');expect(html).not.toContain('/api/tasks/tsk_approved_actions/plan');expect(html).not.toContain('/api/tasks/tsk_approved_actions"');
  });
  it('shows live provider activity with role and model identity',()=>{
    const state:State={projects:[{id:'prj_live_activity',name:'Activity project',tasks:[{id:'tsk_live_activity',title:'Live task',runs:[{id:'run_live_activity',status:'running',assignments:[{id:'asgn_live_worker',roleId:'worker',status:'running',requestedConfig:{harnessId:'codex',model:'gpt-6-sol'}},{id:'asgn_live_reviewer',roleId:'reviewer',status:'running',requestedConfig:{harnessId:'anthropic',model:'claude-sonnet'}}]}]}]},{id:'prj_other',name:'Other project',plannerAssignments:[{id:'asgn_other_planner',roleId:'planner',status:'running'}]}],roles:[{id:'worker',name:'Worker',enabled:true},{id:'reviewer',name:'Reviewer',enabled:true},{id:'planner',name:'Planner',enabled:true}],events:[{id:'evt_provider_activity',type:'assignment.progress',entityType:'assignment',entityId:'asgn_live_worker',at:'2026-09-24T12:00:00.000Z',data:{assignmentId:'asgn_live_worker',providerEvent:{response:{activity:{kind:'tool',summary:'Reading src/index.ts'}}}}},{id:'evt_future_activity',type:'response.activity',entityType:'assignment',entityId:'asgn_live_reviewer',at:'2026-09-24T12:01:00.000Z',data:{assignmentId:'asgn_live_reviewer',roleId:'reviewer',model:'claude-sonnet',activity:{kind:'phase',summary:'Reviewing verified diff'}}},{id:'evt_other_project_activity',type:'assignment.progress',entityType:'assignment',entityId:'asgn_other_planner',at:'2026-09-24T12:02:00.000Z',data:{assignmentId:'asgn_other_planner',providerEvent:{response:{activity:{kind:'tool',summary:'SECRET unrelated project update'}}}}}]};
    const html=renderToStaticMarkup(createElement(App,{initialState:state,initialCliUsage:{harnesses:[{harnessId:'codex',windows:{fiveHour:{status:'available',usedPercent:27,remainingPercent:73,resetsAt:'2026-09-24T18:00:00.000Z'},weekly:{status:'unsupported'}}}]}}));
    expect(html).toContain('Live Response');expect(html).toContain('Worker · gpt-6-sol');expect(html).toContain('Tool · Reading src/index.ts');expect(html).toContain('Reviewer · claude-sonnet');expect(html).toContain('Phase · Reviewing verified diff');expect(html).not.toContain('SECRET unrelated project update');expect(html).toContain('>Usage</button>');expect(html).not.toContain('73%');expect(html).not.toContain('Quota data is shown when the connected harness reports it.');
    const treeIndex=html.indexOf('class="tree card"'),treeContentIndex=html.indexOf('class="tree-content"',treeIndex),inspectorIndex=html.indexOf('aria-label="Inspector"'),liveIndex=html.indexOf('aria-label="Live Response"'),githubIndex=html.indexOf('aria-label="GitHub"');
    expect(treeIndex).toBeGreaterThan(-1);expect(treeContentIndex).toBeGreaterThan(treeIndex);expect(html).toContain('<summary>Repository details</summary>');expect(html).toContain('>History</button>');expect(html).toContain('>Usage</button>');
    expect(html).toContain('class="usage-dock" aria-label="Harness and measured usage"');expect(html).toContain('Project</span><b>No measured usage reported</b>');expect(html).toContain('Selected run</span><b>No measured usage reported</b>');expect(html).toContain('role="group" aria-label="Codex 5 hour usage"');expect(html).toContain('aria-valuenow="27"');expect(html).not.toContain('aria-label="Harness usage"');expect(html).not.toContain('Project details · usage &amp; activity');expect(inspectorIndex).toBeGreaterThan(treeContentIndex);expect(liveIndex).toBeGreaterThan(inspectorIndex);expect(githubIndex).toBeGreaterThan(liveIndex);expect(html.match(/aria-label="Live Response"/g)).toHaveLength(1);expect(html.match(/aria-label="GitHub"/g)).toHaveLength(1);expect(html).not.toContain('Hierarchy from local state');
    expect(html).toContain('role="separator" aria-orientation="vertical" aria-label="Resize project tree"');expect(html).toContain('aria-valuemin="180" aria-valuemax="360" aria-valuenow="220" tabindex="0"');expect(html).toContain('title="Live task"');expect(html).toContain('style="--tree-width:220px"');
  });
  it('keeps quotas in the sidebar and offers a dedicated Usage view',()=>{
    const state:State={projects:[{id:'prj_usage_groups',name:'Usage groups'}],roles:[]};
    const html=renderToStaticMarkup(createElement(App,{initialState:state,initialCliUsage:{harnesses:[
      {harnessId:'antigravity-cli',groups:[{id:'gemini',label:'Gemini',windows:{fiveHour:{status:'available',usedPercent:22,remainingPercent:78,resetsAt:'2026-09-24T18:00:00.000Z'},weekly:{status:'unsupported'}}},{id:'claude',label:'Claude',windows:{weekly:{status:'available',usedPercent:41,remainingPercent:59}}}]},
      {harnessId:'antigravity-cli',windows:{fiveHour:{status:'available',usedPercent:45,remainingPercent:55}}},
      {harnessId:'claude-code',windows:{fiveHour:{status:'available',usedPercent:33,remainingPercent:67,observedAt:'2026-09-24T12:00:00.000Z'},weekly:{status:'unavailable'}}},
      {harnessId:'codex-cli',windows:{fiveHour:{status:'unavailable'},weekly:{status:'available',usedPercent:12,remainingPercent:88}}},
    ]}}));
    const inspectorIndex=html.indexOf('aria-label="Inspector"');
    expect(html).toContain('>Usage</button>');expect(html).toContain('>History</button>');expect(html).toContain('class="usage-dock" aria-label="Harness and measured usage"');expect(html).not.toContain('aria-label="Harness usage"');expect(inspectorIndex).toBeGreaterThan(html.indexOf('class="tree card"'));
    expect(html).toContain('Antigravity · Gemini');expect(html).toContain('Claude');expect(html).toContain('Codex');expect(html).not.toContain('Quota group');expect(html).not.toContain('CLI USAGE');expect(html).not.toContain('Hierarchy from local state');expect(html).toContain('aria-valuenow="22"');expect(html).toContain('aria-valuenow="45"');expect(html).toContain('aria-valuenow="33"');expect(html).toContain('aria-valuenow="12"');
  });
  it('defaults role configuration to an available scope when no run exists',()=>{
    const state:State={projects:[{id:'prj_no_run',name:'No run project',tasks:[{id:'tsk_no_run',title:'Ready task',runs:[]}]}],roles:[{id:'worker',name:'Worker',enabled:true,config:{harnessId:'codex',model:'gpt-6-sol'},availableConfigs:[{harnessId:'codex',model:'gpt-6-sol'}]}]};
    const html=renderToStaticMarkup(createElement(App,{initialState:state}));
    expect(html).toContain('class="outline small settings-button" type="button">Settings</button>');expect(html).not.toContain('aria-label="Configuration scope"');expect(html).not.toContain('id="roles"');expect(html).not.toContain('/api/runs/undefined/roles/worker/config');
  });
});
