import { id, now, validateRoleConfig, type Assignment, type Event, type Guidance, type RoleConfig, type State, type Role, type Run, type Usage } from './domain.js';
import { JsonStore } from './store.js';

export interface UhpAdapter {
  submit(input: { submissionId: string; assignmentId: string; runId: string; roleId: string; taskId: string; projectId: string; prompt: string; config: Record<string, unknown>; idempotencyKey: string; onEvent?:(event:{type?:string;responseId?:string;sessionId?:string;event:Record<string,unknown>})=>void|Promise<void> }): Promise<{ externalId: string; responseId?: string; sessionId?: string; status?: string; output?: unknown; outputText?: string; result?: unknown; actualModel?:string; requestedModel?:string; selectedHarnessId?:string; modelFallback?:boolean; boundsApplied?:boolean; ignoredFields?:string[]; usage?:{inputTokens?:number;outputTokens?:number;totalTokens?:number;cachedInputTokens?:number;requestCount?:number}|null; runtimeMs?:number }>;
  cancel(input: { submissionId: string; externalId?: string; idempotencyKey: string }): Promise<{ status: string }>;
  retrieve?(responseId:string):Promise<{id:string;status:string;metadata?:Record<string,unknown>;model?:string;output_text?:string;output?:unknown;error?:unknown;usage?:{input_tokens?:number;output_tokens?:number;total_tokens?:number;input_tokens_details?:{cached_tokens?:number};cached_input_tokens?:number;request_count?:number;requests?:number}|null}>;
  discover?(refresh?:boolean): Promise<{ version:string; capabilities:Record<string,boolean>; harnesses:Array<{id:string;models?:Array<{id:string;available?:boolean}>}>; models?:Array<{id:string;harnessId?:string;available?:boolean}> }>;
}
export interface HindsightAdapter { ensureBank?(projectId:string):Promise<{status:'ready'|'degraded'}>; recall(projectId:string,query:string):Promise<{status:'ready'|'degraded';bankId:string;memories:Array<{text:string}>;error?:string}>; retainOutcome(outcome:{projectId:string;submissionId:string;runId:string;roleId:string;taskId:string;outcome:string;summary?:string;humanApproved:true}):Promise<{status:'accepted'|'degraded';bankId:string;operationId?:string;error?:string}> }
const event = (type: string, entityType: string, entityId: string, data: Record<string, unknown> = {}): Event => ({ id: id('evt'), type, entityType, entityId, at: now(), data });
const must = <T>(item: T | undefined, what: string): T => { if (!item) throw Object.assign(new Error(`${what} not found`), { statusCode: 404 }); return item; };

export class Controller {
  private discovery?: { version:string; capabilities:Record<string,boolean>; harnesses:Array<{id:string;models?:Array<{id:string;available?:boolean}>}>; models?:Array<{id:string;harnessId?:string;available?:boolean}> };
  private discoveryError?: string;
  private memoryServiceState: 'ready'|'degraded'|'unavailable'|'not_configured';
  constructor(readonly store: JsonStore, readonly uhp: UhpAdapter, readonly memoryConfigured=false, readonly uhpConfigured=false, private readonly configuredRoleChoice?:RoleConfig, private readonly hindsight?:HindsightAdapter,private readonly taskTimeoutSeconds=300) {this.memoryServiceState=memoryConfigured?'unavailable':'not_configured';}
  async state(): Promise<State> { const state=await this.store.load();for(const project of state.projects){const assignments=project.tasks.flatMap(t=>t.runs.flatMap(r=>r.assignments));project.usage=aggregate(assignments.map(a=>a.usage));project.usageByHarnessModel=groupUsage(assignments);for(const task of project.tasks)for(const run of task.runs){run.usage=aggregate(run.assignments.map(a=>a.usage));run.usageByRole=Object.fromEntries([...new Set(run.assignments.map(a=>a.roleId))].map(role=>[role,aggregate(run.assignments.filter(a=>a.roleId===role).map(a=>a.usage))]).filter(([,v])=>!!v));run.usageByHarnessModel=groupUsage(run.assignments);}}for(const role of state.roles){const assignments=state.projects.flatMap(p=>p.tasks.flatMap(t=>t.runs.flatMap(r=>r.assignments))).filter(a=>a.roleId===role.id);role.usage=aggregate(assignments.map(a=>a.usage));role.usageByHarnessModel=groupUsage(assignments);}return state; }
  async serviceStatus() { const discovery=this.discovery?{version:this.discovery.version,capabilities:this.discovery.capabilities,harnesses:this.discovery.harnesses.map(h=>({id:h.id,models:[...(h.models??[]),...(this.discovery!.models??[]).filter(m=>(m as any).harnessId===h.id)]}))}:undefined;return { uhp:{status:this.discovery?'ready':this.discoveryError?'degraded':this.uhpConfigured?'unavailable':'not_configured',configured:this.uhpConfigured,discovery,error:this.discoveryError},memory:{status:this.memoryServiceState,configured:this.memoryConfigured} }; }
  async refreshDiscovery() {
    if(!this.uhpConfigured||!this.uhp.discover){this.discoveryError=undefined;return;}
    try { this.discovery=await this.uhp.discover(true); this.discoveryError=undefined; await this.store.mutate(s=>{const configs:RoleConfig[]=this.discovery!.harnesses.flatMap(h=>[...(h.models??[]),...(this.discovery!.models??[]).filter(m=>(m as any).harnessId===h.id)].filter(m=>m.available!==false).map(m=>({harnessId:h.id,model:m.id})));for(const role of s.roles){role.availableConfigs=structuredClone(configs);role.enabled=configs.length>0;if(this.configuredRoleChoice&&configs.some(c=>c.harnessId===this.configuredRoleChoice!.harnessId&&c.model===this.configuredRoleChoice!.model)&&!role.config.harnessId)role.config=structuredClone(this.configuredRoleChoice);}s.events.push(event('uhp.discovery_updated','service','uhp',{version:this.discovery!.version,configCount:configs.length}));}); }
    catch(error){this.discovery=undefined;this.discoveryError=error instanceof Error?error.message:String(error);await this.store.mutate(s=>{for(const role of s.roles){role.enabled=false;role.availableConfigs=[];}s.events.push(event('uhp.discovery_failed','service','uhp',{error:this.discoveryError}));});}
  }

  async createProject(name: string): Promise<unknown> {
    const clean = name.trim(); if (!clean) throw new Error('Project name is required');
    const project=await this.store.mutate(s => { const defaults=Object.fromEntries(s.roles.filter(r=>r.config.harnessId&&r.config.model).map(r=>[r.id,structuredClone(r.config)]));const project = { id: id('prj'), name: clean, status: 'active' as const, defaultRoleConfigs: defaults, createdAt: now(), tasks: [] }; s.projects.push(project); s.events.push(event('project.created','project',project.id,{name:clean})); return project; });
    if(this.hindsight?.ensureBank)void this.hindsight.ensureBank((project as any).id).then(result=>this.memoryServiceState=result.status==='ready'?'ready':'degraded').catch(()=>this.memoryServiceState='degraded');
    return project;
  }
  async selectRoleConfig(roleId:string,config:RoleConfig,projectId?:string,runId?:string):Promise<unknown>{return this.store.mutate(s=>{const role=must(s.roles.find(r=>r.id===roleId),'Role');validateRoleConfig(role,config);if(runId){const run=this.findRun(s,runId);run.roleConfigs[roleId]=structuredClone(config);if(roleId==='planner'||roleId==='orchestrator'){const old=run.sessions[roleId];old.status='rotated';old.rotatedAt=now();run.sessionHistory.push(structuredClone(old));run.sessions[roleId]=newSession(roleId,config,old.generation+1);if(roleId==='planner')delete run.plannerSessionId;else delete run.orchestratorSessionId;}s.events.push(event('role_config.selected','run',runId,{roleId,config,scope:'run',sessionRotated:roleId==='planner'||roleId==='orchestrator'}));return run.roleConfigs[roleId];}if(projectId){const project=must(s.projects.find(p=>p.id===projectId),'Project');project.defaultRoleConfigs[roleId]=structuredClone(config);s.events.push(event('role_config.selected','project',projectId,{roleId,config,scope:'project'}));return project.defaultRoleConfigs[roleId];}role.config=structuredClone(config);s.events.push(event('role_config.selected','role',roleId,{config,scope:'global'}));return role.config;});}
  async createTask(projectId: string, title: string): Promise<unknown> {
    const clean = title.trim(); if (!clean) throw new Error('Task title is required');
    return this.store.mutate(s => { const p = must(s.projects.find(x=>x.id===projectId),'Project'); const task = { id:id('tsk'), title:clean, status:'ready' as const, createdAt:now(), runs:[] }; p.tasks.push(task); s.events.push(event('task.created','task',task.id,{projectId,title:clean})); return task; });
  }
  async createRun(taskId: string): Promise<unknown> {
    return this.store.mutate(s => { const {task}=this.findTask(s,taskId); const project=this.findProject(s,taskId); const roleConfigs=structuredClone(project.defaultRoleConfigs); for(const roleId of ['planner','orchestrator']) roleConfigs[roleId]??=structuredClone(must(s.roles.find(r=>r.id===roleId),'Role').config); const t=now(); const blank={harnessId:'',model:''};const run:Run = { id:id('run'), status:'planning', createdAt:t, sessions:{planner:newSession('planner',roleConfigs.planner??blank),orchestrator:newSession('orchestrator',roleConfigs.orchestrator??blank)}, sessionHistory:[], roleConfigs, guidance:[], assignments:[], reviews:[] }; task.status='active'; task.runs.push(run); s.events.push(event('run.created','run',run.id,{taskId,sessions:run.sessions})); return run; });
  }
  async rotateSession(runId:string,roleId:string):Promise<unknown>{if(roleId!=='planner'&&roleId!=='orchestrator')throw new Error('Only Planner and Orchestrator have long-lived sessions');return this.store.mutate(s=>{const run=this.findRun(s,runId),old=run.sessions[roleId],config=run.roleConfigs[roleId]??old.config;old.status='rotated';old.rotatedAt=now();run.sessionHistory.push(structuredClone(old));const session=newSession(roleId,config,old.generation+1);run.sessions[roleId]=session;if(roleId==='planner')delete run.plannerSessionId;else delete run.orchestratorSessionId;s.events.push(event('session.rotated','session',session.localId,{runId,roleId,generation:session.generation,previousLocalId:old.localId,previousUhpSessionId:old.uhpSessionId}));return session;});}
  async addGuidance(runId: string, text: string): Promise<unknown> {
    const clean=text.trim(); if(!clean) throw new Error('Guidance text is required');
    const guidance=await this.store.mutate(s=>{ const run=this.findRun(s,runId); const g: Guidance={id:id('guide'),sequence:Math.max(0,...run.guidance.map(x=>x.sequence))+1,text:clean,status:'queued',createdAt:now()}; run.guidance.push(g); run.status='waiting_guidance'; s.events.push(event('guidance.added','guidance',g.id,{runId,sequence:g.sequence,status:g.status,text:clean})); return g; });
    const run=this.findRun(await this.store.load(),runId);const role=run.roleConfigs.planner??(await this.store.load()).roles.find(r=>r.id==='planner')?.config;
    if(role?.harnessId&&role.model){try{const turn=await this.assign(runId,'planner',`Operator guidance (sequence ${guidance.sequence}):\n${clean}`,role);const text=typeof turn.result==='string'?turn.result:undefined;const saved=await this.store.mutate(s=>{const g=this.findRun(s,runId).guidance.find(x=>x.id===guidance.id)!;g.plannerAssignmentId=turn.id;g.plannerReply=text;s.events.push(event('planner.turn_completed','guidance',g.id,{assignmentId:turn.id,hasReply:!!text}));return g;});const latest=this.findRun(await this.store.load(),runId);if(!latest.assignments.some(a=>a.roleId==='worker'&&['submitting','submitted','running','cancel_requested'].includes(a.status)))try{await this.deliverGuidanceCheckpoint(runId);}catch{/* keep durable guidance queued when orchestration is not configured or handoff is unavailable */}return this.findRun(await this.store.load(),runId).guidance.find(g=>g.id===saved.id)!;}catch(error){await this.store.mutate(s=>{s.events.push(event('planner.turn_failed','guidance',guidance.id,{error:error instanceof Error?error.message:String(error)}));});}}
    else await this.store.mutate(s=>{s.events.push(event('planner.turn_unavailable','guidance',guidance.id,{reason:'No explicitly selected, discovered Planner configuration'}));});
    return this.findRun(await this.store.load(),runId).guidance.find(x=>x.id===guidance.id);
  }
  async acknowledgeGuidance(guidanceId: string, acknowledgment: 'applied'|'replan'|'waiting'): Promise<unknown> {
    if(!['applied','replan','waiting'].includes(acknowledgment)) throw new Error('Invalid guidance acknowledgment');
    return this.store.mutate(s=>{ const g=must(s.projects.flatMap(p=>p.tasks).flatMap(t=>t.runs).flatMap(r=>r.guidance).find(x=>x.id===guidanceId),'Guidance'); if(g.status!=='delivered')throw Object.assign(new Error('Guidance must reach a safe checkpoint before acknowledgment'),{statusCode:409});g.status=acknowledgment; g.acknowledgment=acknowledgment; g.acknowledgedAt=now();const run=this.findGuidanceRun(s,guidanceId);if(!run.guidance.some(x=>x.status==='queued'||x.status==='delivered'))run.status='planning';s.events.push(event('guidance.acknowledged','guidance',g.id,{acknowledgment}));return g; });
  }
  async deliverGuidanceCheckpoint(runId:string):Promise<Guidance[]>{
    const state=await this.store.load(),run=this.findRun(state,runId);
    if(run.assignments.some(a=>['submitting','submitted','running','cancel_requested'].includes(a.status)))throw Object.assign(new Error('Guidance can only be handed off when all assignments have reached a safe checkpoint'),{statusCode:409});
    const queued=run.guidance.filter(g=>g.status==='queued').sort((a,b)=>a.sequence-b.sequence);if(!queued.length)return [];
    const role=run.roleConfigs.orchestrator??state.roles.find(r=>r.id==='orchestrator')?.config;if(!role?.harnessId||!role.model)throw Object.assign(new Error('No explicitly selected, discovered Orchestrator configuration'),{statusCode:409});
    const ids=queued.map(g=>g.id),handoff=queued.map(g=>`${g.id} | ${g.sequence}. ${g.text}`).join('\n');const plannerNotes=run.assignments.filter(a=>a.roleId==='planner'&&a.status==='succeeded').map(a=>typeof a.result==='string'?a.result:JSON.stringify(a.result)).join('\n').slice(0,6000);
    const prompt=`Safe-checkpoint handoff. Review the guidance in order. Return exactly one JSON object and no prose: {"acknowledgments":[{"guidanceId":"...","action":"applied|replan|waiting","reason":"..."}]}. Include every supplied guidanceId exactly once. Use applied only if your orchestration state confirms it was applied; use replan if the plan must change; otherwise use waiting.\n\nPlanner context:\n${plannerNotes||'No Planner response recorded.'}\n\nOrdered guidance (IDs are authoritative):\n${handoff}`;
    const orchestration=await this.assign(runId,'orchestrator',prompt,role);
    const parsed=parseGuidanceAcknowledgments(orchestration.result,ids);
    return this.store.mutate(s=>{const current=this.findRun(s,runId),byId=new Map(parsed?.map(x=>[x.guidanceId,x]));for(const g of current.guidance.filter(g=>g.status==='queued')){g.status='delivered';g.checkpointHandoffAssignmentId=orchestration.id;s.events.push(event('guidance.delivered','guidance',g.id,{runId,sequence:g.sequence,orchestratorAssignmentId:orchestration.id}));const ack=byId.get(g.id);if(ack){g.status=ack.action;g.acknowledgment=ack.action;g.acknowledgedAt=now();s.events.push(event('guidance.acknowledged','guidance',g.id,{acknowledgment:ack.action,reason:ack.reason,source:'orchestrator',assignmentId:orchestration.id}));}}if(!parsed)s.events.push(event('guidance.handoff_invalid','run',runId,{assignmentId:orchestration.id,reason:'Orchestrator response did not contain a valid complete JSON acknowledgment envelope'}));if(!current.guidance.some(g=>g.status==='queued'||g.status==='delivered'))current.status='planning';return current.guidance.filter(g=>g.checkpointHandoffAssignmentId===orchestration.id);});
  }
  async assign(runId: string, roleId: string, prompt: string, config?: RoleConfig): Promise<Assignment> {
    const submissionId=id('sub'), assignmentId=id('asgn'), key=id('idem');
    const prep = await this.store.mutate(s=>{ const {project,task,run}=this.findRunContext(s,runId); const role=must(s.roles.find(x=>x.id===roleId),'Role'); const requested=config ?? run.roleConfigs[roleId] ?? project.defaultRoleConfigs[roleId] ?? role.config; validateRoleConfig(role,requested); if(!prompt.trim()) throw new Error('Assignment prompt is required'); const a: Assignment={id:assignmentId,roleId,status:'submitting',requestedConfig:structuredClone(requested),prompt:prompt.trim(),submissionId,idempotencyKey:key,createdAt:now()}; run.assignments.push(a); if(roleId==='worker')run.status='running';else if(!run.guidance.some(g=>g.status==='queued'||g.status==='delivered'))run.status=roleId==='reviewer'?'review':'planning';s.events.push(event('assignment.submission_intent','assignment',a.id,{runId,roleId,submissionId,idempotencyKey:key,requestedConfig:requested}));return {a,project,task,run}; });
    return this.submitExisting(prep.project.id,prep.task.id,prep.run.id,prep.a.id);
  }
  async recover(): Promise<void> {
    const s=await this.store.load();
    for (const p of s.projects) for(const t of p.tasks) for(const r of t.runs) for(const a of r.assignments) if(a.status==='submitting'||a.status==='running') { if(a.responseId&&this.uhp.retrieve) await this.reconcileExisting(a.id).catch(()=>undefined); else if(a.status==='submitting') await this.submitExisting(p.id,t.id,r.id,a.id,true).catch(()=>undefined); }
  }
  async reconcileRunning():Promise<void>{const s=await this.store.load();for(const p of s.projects)for(const t of p.tasks)for(const r of t.runs)for(const a of r.assignments)if(a.status==='running'&&a.responseId)await this.reconcileExisting(a.id).catch(()=>undefined);}
  async refreshAssignment(assignmentId:string):Promise<unknown>{return this.reconcileExisting(assignmentId).then(async()=>this.findAssignment(await this.store.load(),assignmentId).a);}
  private async reconcileExisting(assignmentId:string):Promise<void>{const snapshot=await this.store.load(),{a}=this.findAssignment(snapshot,assignmentId);if(!a.responseId||!this.uhp.retrieve)return;const response=await this.uhp.retrieve(a.responseId);const terminal=normalizeStatus(response.status);if(['succeeded','failed','needs_revision','cancelled'].includes(terminal)){await this.store.mutate(s=>{const {a:r,run}=this.findAssignment(s,assignmentId);r.status=terminal;r.result=response.output_text??response.output??response.error;r.externalId=response.id;const meta=response.metadata??{};if(typeof meta.session_id==='string')r.sessionId=meta.session_id;if(typeof response.model==='string'&&typeof meta.harness_id==='string'){r.actualConfig={harnessId:meta.harness_id,model:response.model};r.configOutcome=r.actualConfig.model===r.requestedConfig.model&&r.actualConfig.harnessId===r.requestedConfig.harnessId?'confirmed':'substituted';}if(response.usage&&typeof response.usage==='object'){const u=response.usage,usage:Usage={measured:true};const copy=(source:unknown,target:'inputTokens'|'outputTokens'|'totalTokens'|'cachedInputTokens'|'requestCount')=>{if(typeof source==='number'&&Number.isFinite(source))usage[target]=source;};copy(u.input_tokens,'inputTokens');copy(u.output_tokens,'outputTokens');copy(u.total_tokens,'totalTokens');copy(u.input_tokens_details?.cached_tokens??u.cached_input_tokens,'cachedInputTokens');copy(u.request_count??u.requests,'requestCount');if(Object.keys(usage).length>1)r.usage={...r.usage,...usage};}if(r.roleId==='planner'||r.roleId==='orchestrator'){const session=run.sessions[r.roleId];session.responseId=response.id;if(r.sessionId)session.uhpSessionId=r.sessionId;if(r.roleId==='planner')run.plannerSessionId=session.uhpSessionId;else run.orchestratorSessionId=session.uhpSessionId;}s.events.push(event('assignment.reconciled','assignment',r.id,{responseId:r.responseId,status:terminal}));});}else await this.store.mutate(s=>{const {a:r}=this.findAssignment(s,assignmentId);r.status='running';s.events.push(event('assignment.reconciled','assignment',r.id,{responseId:r.responseId,status:response.status}));});}
  private async submitExisting(projectId:string,taskId:string,runId:string,assignmentId:string,retrying=false): Promise<Assignment> {
    const snapshot=await this.store.load(); const {a}=this.findAssignment(snapshot,assignmentId); if(a.status!=='submitting') return a;
    if(retrying&&this.discovery&&this.discovery.capabilities.idempotency!==true){await this.store.mutate(s=>{s.events.push(event('assignment.recovery_blocked','assignment',assignmentId,{reason:'UHP idempotency is unavailable; controller will not repeat the submission'}));});return a;}
    try {
      const context=await this.store.load();const {run}=this.findAssignment(context,assignmentId);const uhpSession=a.roleId==='planner'||a.roleId==='orchestrator'?run.sessions[a.roleId]:undefined;const config={...(a.requestedConfig.options??{}),...a.requestedConfig,timeoutSeconds:(a.requestedConfig.options?.timeoutSeconds??this.taskTimeoutSeconds),...(uhpSession&&uhpSession.responseId?{previousResponseId:uhpSession.responseId}:{})};
      let prompt=a.prompt; if(this.hindsight){const memory=await this.hindsight.recall(projectId,a.prompt);this.memoryServiceState=memory.status==='ready'?'ready':'degraded';if(memory.memories.length)prompt=`Relevant project memory (reference only):\n${memory.memories.map(x=>x.text.slice(0,1200)).join('\n---\n').slice(0,6000)}\n\nCurrent assignment:\n${a.prompt}`;await this.store.mutate(s=>{s.events.push(event('memory.recall','project',projectId,{status:memory.status,bankId:memory.bankId,count:memory.memories.length,...(memory.error?{error:memory.error}:{})}));});}
      const response=await this.uhp.submit({submissionId:a.submissionId,assignmentId:a.id,runId,roleId:a.roleId,taskId,projectId,prompt,config,idempotencyKey:a.idempotencyKey,onEvent:async progress=>{await this.store.mutate(s=>{const {a:r,run}=this.findAssignment(s,assignmentId);if(progress.responseId){r.externalId??=progress.responseId;r.responseId??=progress.responseId;r.status='running';}if(progress.sessionId)r.sessionId=progress.sessionId;if(r.roleId==='planner'||r.roleId==='orchestrator'){const session=run.sessions[r.roleId];if(progress.responseId)session.responseId=progress.responseId;if(progress.sessionId){session.uhpSessionId=progress.sessionId;session.status='active';if(r.roleId==='planner')run.plannerSessionId=progress.sessionId;else run.orchestratorSessionId=progress.sessionId;}}s.events.push(event('assignment.progress','assignment',r.id,{type:progress.type,responseId:progress.responseId,sessionId:progress.sessionId,providerEvent:progress.event}));});}});
      return this.store.mutate(s=>{const {a:r,run}=this.findAssignment(s,assignmentId); r.externalId=response.externalId; r.responseId=response.responseId; r.sessionId=response.sessionId; if(response.actualModel&&response.selectedHarnessId)r.actualConfig={harnessId:response.selectedHarnessId,model:response.actualModel};r.configOutcome=r.actualConfig?((response.modelFallback||response.actualModel!==r.requestedConfig.model||response.selectedHarnessId!==r.requestedConfig.harnessId)?'substituted':'confirmed'):'unavailable';r.configNotes={...(response.boundsApplied!==undefined?{boundsApplied:response.boundsApplied}:{}),...(response.ignoredFields?.length?{ignoredFields:[...response.ignoredFields]}:{})};if(response.usage&&Object.keys(response.usage).length)r.usage={...response.usage,measured:true,...(response.runtimeMs!==undefined?{runtimeMs:response.runtimeMs}:{})};else if(response.runtimeMs!==undefined)r.usage={runtimeMs:response.runtimeMs,measured:true};r.status=normalizeStatus(response.status);r.result=response.output ?? response.outputText ?? response.result;if(r.roleId==='planner'||r.roleId==='orchestrator'){const session=run.sessions[r.roleId];session.responseId=response.responseId??response.externalId;if(response.sessionId)session.uhpSessionId=response.sessionId;session.status='active';if(r.roleId==='planner')run.plannerSessionId=session.uhpSessionId;else run.orchestratorSessionId=session.uhpSessionId;}const pendingGuidance=run.guidance.some(g=>g.status==='queued'||g.status==='delivered');const workerActive=run.assignments.some(a=>a.id!==r.id&&a.roleId==='worker'&&['submitting','submitted','running','cancel_requested'].includes(a.status));run.status=r.status==='failed'?'failed':r.status==='needs_revision'?'review':pendingGuidance?'waiting_guidance':r.roleId==='worker'&&r.status==='succeeded'?'review':r.roleId==='reviewer'?'review':workerActive?'running':'planning';s.events.push(event('assignment.submitted','assignment',r.id,{submissionId:r.submissionId,externalId:r.externalId,responseId:r.responseId,sessionId:r.sessionId,status:r.status,requestedConfig:r.requestedConfig,actualConfig:r.actualConfig,configOutcome:r.configOutcome,usage:r.usage}));return r;});
    } catch(error) { await this.store.mutate(s=>{const {a:r}=this.findAssignment(s,assignmentId); r.error=error instanceof Error?error.message:String(error); s.events.push(event('assignment.submit_uncertain','assignment',r.id,{error:r.error,idempotencyKey:r.idempotencyKey}));}); throw error; }
  }
  async cancelAssignment(assignmentId:string): Promise<unknown> {
    const item=await this.store.mutate(s=>{const {a}=this.findAssignment(s,assignmentId); if(['cancelled','succeeded','failed'].includes(a.status)) return a; a.status='cancel_requested'; a.cancelIdempotencyKey ??= id('idem-cancel'); s.events.push(event('assignment.cancel_intent','assignment',a.id,{idempotencyKey:a.cancelIdempotencyKey})); return a;});
    if(item.status!=='cancel_requested') return item;
    const response=await this.uhp.cancel({submissionId:item.submissionId,externalId:item.externalId,idempotencyKey:item.cancelIdempotencyKey!});
    return this.store.mutate(s=>{const {a,run}=this.findAssignment(s,assignmentId);a.status=response.status==='cancelled'?'cancelled':'cancel_requested';if(a.status==='cancelled'&&run.guidance.some(g=>g.status==='queued'))run.status='waiting_guidance';s.events.push(event('assignment.cancel_result','assignment',a.id,{status:response.status}));return a;});
  }
  async addReview(runId:string,input:{reviewerAssignmentId:string;implementationAssignmentIds:string[];verdict:'clear'|'changes_requested'|'rejected';scope:string[];summary:string}):Promise<unknown>{return this.store.mutate(s=>{const run=this.findRun(s,runId),reviewer=must(run.assignments.find(a=>a.id===input.reviewerAssignmentId),'Reviewer assignment');if(reviewer.roleId!=='reviewer'||reviewer.status!=='succeeded')throw new Error('Reviewer proposal requires a completed Reviewer assignment');if(!input.implementationAssignmentIds.length||input.implementationAssignmentIds.includes(reviewer.id))throw new Error('Reviewer cannot approve its own implementation');for(const assignmentId of input.implementationAssignmentIds){const impl=must(run.assignments.find(a=>a.id===assignmentId),'Implementation assignment');if(impl.roleId!=='worker'||impl.status!=='succeeded')throw new Error('Review scope must contain completed Worker assignments');}const implemented=run.assignments.filter(a=>a.roleId==='worker'&&a.status==='succeeded').map(a=>a.id).sort();if(JSON.stringify(implemented)!==JSON.stringify([...input.implementationAssignmentIds].sort()))throw new Error('Reviewer proposal must cover every completed Worker assignment');if(!['clear','changes_requested','rejected'].includes(input.verdict)||!input.scope.length)throw new Error('Review verdict and scope are required');const review={id:id('review'),status:'proposed' as const,reviewerAssignmentId:reviewer.id,implementationAssignmentIds:[...input.implementationAssignmentIds],verdict:input.verdict,scope:input.scope.map(x=>x.trim()).filter(Boolean),summary:input.summary.trim(),createdAt:now()};run.reviews.push(review);run.status='review';s.events.push(event('review.proposed','review',review.id,{runId,verdict:review.verdict,implementationAssignmentIds:review.implementationAssignmentIds,authority:'unverified-agent-proposal'}));return review;});}
  async recordValidation(runId:string,input:{passed:boolean;checks:Array<{name:string;passed:boolean;details?:string}>;gitEvidence?:{commit?:string;tree?:string;changedPaths?:string[]}}):Promise<unknown>{return this.store.mutate(s=>{const run=this.findRun(s,runId);if(!run.reviews.some(r=>r.status==='verified'&&r.verdict==='clear'))throw Object.assign(new Error('A controller-verified clear reviewer verdict is required before validation'),{statusCode:409});if(!Array.isArray(input.checks)||!input.checks.length||input.checks.some(c=>!c.name||typeof c.passed!=='boolean'))throw new Error('Validation requires named check results');const checks=structuredClone(input.checks),reportedPassed=input.passed&&checks.every(c=>c.passed);const record={id:id('valid'),status:'unverified' as const,passed:false,reportedPassed,checks,createdAt:now(),...(input.gitEvidence?{gitEvidence:{status:'unverified' as const,...input.gitEvidence,submittedAt:now()}}:{})};run.validation=record;run.status='validation';s.events.push(event('validation.reported','validation',record.id,{runId,reportedPassed,authority:'unverified-client-report',gitEvidenceStatus:record.gitEvidence?.status??'missing'}));return record;});}
  async approveRun(runId:string,input:{approved:boolean;evidenceCommit?:string}):Promise<unknown>{const approval=await this.store.mutate(s=>{const context=this.findRunContext(s,runId),run=context.run;if(!input.approved)throw Object.assign(new Error('Run was not approved'),{statusCode:409});if(!run.validation||run.validation.status!=='passed'||!run.reviews.some(r=>r.status==='verified'&&r.verdict==='clear'))throw Object.assign(new Error('Approval requires controller-verified passing validation and a clear reviewer verdict'),{statusCode:409});if(run.validation.gitEvidence?.status!=='verified')throw Object.assign(new Error('Approval is blocked until Git evidence is independently verified by the controller'),{statusCode:409});const accepted={id:id('approval'),approved:true,evidenceCommit:input.evidenceCommit,createdAt:now()};run.approval=accepted;run.status='completed';s.events.push(event('run.approved','run',run.id,{approvalId:accepted.id}));return {approval:accepted,projectId:context.project.id,taskId:context.task.id,run};});
    if(this.hindsight)for(const a of approval.run.assignments.filter(a=>a.roleId==='worker'&&a.status==='succeeded')){const retained=await this.hindsight.retainOutcome({projectId:approval.projectId,submissionId:a.submissionId,runId,roleId:a.roleId,taskId:approval.taskId,outcome:typeof a.result==='string'?a.result:JSON.stringify(a.result),humanApproved:true});this.memoryServiceState=retained.status==='accepted'?'ready':'degraded';await this.store.mutate(s=>{s.events.push(event('memory.retention','assignment',a.id,{status:retained.status,bankId:retained.bankId,...(retained.operationId?{operationId:retained.operationId}:{}),...(retained.error?{error:retained.error}:{})}));});}
    return approval.approval;}
  private findTask(s:State,id:string) { for(const p of s.projects){const task=p.tasks.find(t=>t.id===id);if(task)return {project:p,task};} throw Object.assign(new Error('Task not found'),{statusCode:404}); }
  private findGuidanceRun(s:State,guidanceId:string):Run { for(const p of s.projects)for(const t of p.tasks)for(const r of t.runs)if(r.guidance.some(g=>g.id===guidanceId))return r;throw Object.assign(new Error('Guidance not found'),{statusCode:404}); }
  private findProject(s:State,taskId:string) { return this.findTask(s,taskId).project; }
  private findRun(s:State,id:string) { for(const p of s.projects)for(const t of p.tasks){const r=t.runs.find(r=>r.id===id);if(r)return r;} throw Object.assign(new Error('Run not found'),{statusCode:404}); }
  private findRunContext(s:State,id:string) { for(const p of s.projects)for(const t of p.tasks){const run=t.runs.find(r=>r.id===id);if(run)return {project:p,task:t,run};} throw Object.assign(new Error('Run not found'),{statusCode:404}); }
  private findAssignment(s:State,id:string) { for(const p of s.projects)for(const t of p.tasks)for(const run of t.runs){const a=run.assignments.find(a=>a.id===id);if(a)return {a,run};} throw Object.assign(new Error('Assignment not found'),{statusCode:404}); }
}
function normalizeStatus(status?:string): Assignment['status'] { if(status==='completed'||status==='succeeded') return 'succeeded'; if(status==='incomplete') return 'needs_revision'; if(status==='failed'||status==='running'||status==='cancelled'||status==='needs_revision') return status; return 'submitted'; }
function newSession(roleId:'planner'|'orchestrator',config:RoleConfig,generation=1):Run['sessions']['planner'] { return {localId:id(`${roleId}-session`),roleId,generation,status:'new',config:structuredClone(config),startedAt:now()}; }
interface GuidanceAck { guidanceId:string; action:'applied'|'replan'|'waiting'; reason:string }
function parseGuidanceAcknowledgments(value:unknown,expectedIds:string[]):GuidanceAck[]|undefined { if(typeof value!=='string')return;try{const parsed=JSON.parse(value) as {acknowledgments?:unknown};if(!parsed||!Array.isArray(parsed.acknowledgments)||parsed.acknowledgments.length!==expectedIds.length)return;const result:GuidanceAck[]=[];for(const item of parsed.acknowledgments){if(!item||typeof item!=='object')return;const x=item as Record<string,unknown>;if(typeof x.guidanceId!=='string'||!['applied','replan','waiting'].includes(String(x.action))||typeof x.reason!=='string'||!x.reason.trim())return;result.push({guidanceId:x.guidanceId,action:x.action as GuidanceAck['action'],reason:x.reason.trim().slice(0,1000)});}if(new Set(result.map(x=>x.guidanceId)).size!==expectedIds.length||expectedIds.some(id=>!result.some(x=>x.guidanceId===id)))return;return result;}catch{return;} }
const usageFields=['inputTokens','outputTokens','totalTokens','cachedInputTokens','runtimeMs','requestCount'] as const;
function aggregate(values:Array<Usage|undefined>):Usage|undefined {const measured=values.filter((x):x is Usage=>!!x&&Object.keys(x).some(k=>usageFields.includes(k as typeof usageFields[number])));if(!measured.length)return;const result:Usage={measured:true};for(const field of usageFields){const numbers=values.map(x=>x?.[field]);if(numbers.length&&numbers.every((x):x is number=>typeof x==='number'&&Number.isFinite(x)))result[field]=numbers.reduce((a,b)=>a+b,0);}return Object.keys(result).length>1?result:undefined;}
function groupUsage(assignments:Assignment[]):Record<string,Usage>|undefined {const groups=new Map<string,Array<Usage|undefined>>();for(const a of assignments){if(!a.actualConfig)continue;const key=`${a.actualConfig.harnessId}/${a.actualConfig.model}`;groups.set(key,[...(groups.get(key)??[]),a.usage]);}const result=Object.fromEntries([...groups.entries()].map(([key,values])=>[key,aggregate(values)]).filter(([,value])=>!!value));return Object.keys(result).length?result as Record<string,Usage>:undefined;}
