import { id, now, validateRoleConfig, type Assignment, type Event, type Guidance, type RoleConfig, type State, type Role, type Run, type Usage } from './domain.js';
import { JsonStore } from './store.js';
import { verifyWorkerSnapshot, reconstructRecordedSnapshot, validateWorkerOutput, fetchBridgeSnapshot, seedBridgeWorkspace, type VerifiedWorkerWorkspace, type ValidationCommand } from './verified-workspace.js';
import { snapshotGitCommit } from './git-workspace.js';
import type { WorkerEvidence, ValidationCheck } from './domain.js';

export interface UhpAdapter {
  submit(input: { submissionId: string; assignmentId: string; runId: string; roleId: string; taskId: string; projectId: string; prompt: string; config: Record<string, unknown>; idempotencyKey: string; onEvent?:(event:{type?:string;responseId?:string;sessionId?:string;event:Record<string,unknown>})=>void|Promise<void> }): Promise<{ externalId: string; responseId?: string; sessionId?: string; status?: string; output?: unknown; outputText?: string; result?: unknown; actualModel?:string; requestedModel?:string; selectedHarnessId?:string; modelFallback?:boolean; boundsApplied?:boolean; ignoredFields?:string[]; usage?:{inputTokens?:number;outputTokens?:number;totalTokens?:number;cachedInputTokens?:number;requestCount?:number}|null; runtimeMs?:number }>;
  cancel(input: { submissionId: string; externalId?: string; idempotencyKey: string }): Promise<{ status: string }>;
  retrieve?(responseId:string):Promise<{id:string;status:string;metadata?:Record<string,unknown>;model?:string;output_text?:string;output?:unknown;error?:unknown;usage?:{input_tokens?:number;output_tokens?:number;total_tokens?:number;input_tokens_details?:{cached_tokens?:number};cached_input_tokens?:number;request_count?:number;requests?:number}|null}>;
  discover?(refresh?:boolean): Promise<{ version:string; capabilities:Record<string,boolean>; harnesses:Array<{id:string;models?:Array<{id:string;available?:boolean}>}>; models?:Array<{id:string;harnessId?:string;available?:boolean}> }>;
}
export interface HindsightAdapter { ensureBank?(projectId:string):Promise<{status:'ready'|'degraded'}>; recall(projectId:string,query:string):Promise<{status:'ready'|'degraded';bankId:string;memories:Array<{text:string}>;error?:string}>; retainOutcome(outcome:{projectId:string;submissionId:string;runId:string;roleId:string;taskId:string;outcome:string;summary?:string;humanApproved:true}):Promise<{status:'accepted'|'degraded';bankId:string;operationId?:string;error?:string}> }
const event = (type: string, entityType: string, entityId: string, data: Record<string, unknown> = {}): Event => ({ id: id('evt'), type, entityType, entityId, at: now(), data });
const must = <T>(item: T | undefined, what: string): T => { if (!item) throw Object.assign(new Error(`${what} not found`), { statusCode: 404 }); return item; };

export class Controller {
  private verifiedWorkspaceConfig?:{repoPath:string;allowedScope:string[];commands:ValidationCommand[];bridgeBaseUrl?:string;timeoutMs?:number;maxOutputBytes?:number};
  private discovery?: { version:string; capabilities:Record<string,boolean>; harnesses:Array<{id:string;models?:Array<{id:string;available?:boolean}>}>; models?:Array<{id:string;harnessId?:string;available?:boolean}> };
  private discoveryError?: string;
  private memoryServiceState: 'ready'|'degraded'|'unavailable'|'not_configured';
  private readonly retentionInFlight = new Set<string>();
  private readonly cancellationInFlight = new Map<string, Promise<unknown>>();
  constructor(readonly store: JsonStore, readonly uhp: UhpAdapter, readonly memoryConfigured=false, readonly uhpConfigured=false, private readonly configuredRoleChoice?:RoleConfig, private readonly hindsight?:HindsightAdapter,private readonly taskTimeoutSeconds=300) {this.memoryServiceState=memoryConfigured?'unavailable':'not_configured';}
  async state(): Promise<State> { const state=await this.store.load();for(const project of state.projects){const assignments=project.tasks.flatMap(t=>t.runs.flatMap(r=>r.assignments));project.usage=aggregate(assignments.map(a=>a.usage));project.usageByHarnessModel=groupUsage(assignments);for(const task of project.tasks)for(const run of task.runs){run.usage=aggregate(run.assignments.map(a=>a.usage));run.usageByRole=Object.fromEntries([...new Set(run.assignments.map(a=>a.roleId))].map(role=>[role,aggregate(run.assignments.filter(a=>a.roleId===role).map(a=>a.usage))]).filter(([,v])=>!!v));run.usageByHarnessModel=groupUsage(run.assignments);}}for(const role of state.roles){const assignments=state.projects.flatMap(p=>p.tasks.flatMap(t=>t.runs.flatMap(r=>r.assignments))).filter(a=>a.roleId===role.id);role.usage=aggregate(assignments.map(a=>a.usage));role.usageByHarnessModel=groupUsage(assignments);}return state; }
  configureVerifiedWorkspace(config:{repoPath:string;allowedScope:string[];commands:ValidationCommand[];bridgeBaseUrl?:string;timeoutMs?:number;maxOutputBytes?:number}):void { if(!config.repoPath||!config.allowedScope.length||!config.commands.length)throw new Error('Workspace repository, allowed scope, and validation commands are required');this.verifiedWorkspaceConfig=structuredClone(config); }
  async pinWorkerBase(runId:string,baseCommit:string):Promise<void>{const config=this.verifiedWorkspaceConfig;if(!config)throw Object.assign(new Error('Verified workspace workflow is not configured'),{statusCode:503});await snapshotGitCommit(config.repoPath,baseCommit);await this.store.mutate(s=>{const run=this.findRun(s,runId);if(run.pinnedBaseCommit&&run.pinnedBaseCommit.toLowerCase()!==baseCommit.toLowerCase())throw Object.assign(new Error('Run base is already pinned'),{statusCode:409});run.pinnedBaseCommit=baseCommit.toLowerCase();s.events.push(event('worker.base_pinned','run',runId,{pinnedBaseCommit:run.pinnedBaseCommit,provenance:'fixture_or_operator'}));});}
  async prepareWorkerWorkspace(runId:string,baseCommit:string):Promise<unknown>{const config=this.verifiedWorkspaceConfig;if(!config?.bridgeBaseUrl)throw Object.assign(new Error('Workspace bridge URL is not configured'),{statusCode:503});const current=this.findRun(await this.store.load(),runId);if(current.workspaceId){if(current.pinnedBaseCommit?.toLowerCase()!==baseCommit.toLowerCase())throw Object.assign(new Error('Run workspace is already pinned to a different base'),{statusCode:409});return current;}await this.pinWorkerBase(runId,baseCommit);const seeded=await seedBridgeWorkspace(config.bridgeBaseUrl,baseCommit);await this.store.mutate(s=>{const run=this.findRun(s,runId);if(run.workspaceId&&run.workspaceId!==seeded.workspaceId)throw Object.assign(new Error('Run already has a different workspace'),{statusCode:409});run.workspaceId=seeded.workspaceId;s.events.push(event('worker.workspace_seeded','run',runId,{workspaceId:run.workspaceId,pinnedBaseCommit:run.pinnedBaseCommit}));});return this.findRun(await this.store.load(),runId);}
  async serviceStatus() { const discovery=this.discovery?{version:this.discovery.version,capabilities:this.discovery.capabilities,harnesses:this.discovery.harnesses.map(h=>({id:h.id,models:[...(h.models??[]),...(this.discovery!.models??[]).filter(m=>(m as any).harnessId===h.id)]}))}:undefined;return { uhp:{status:this.discovery?'ready':this.discoveryError?'degraded':this.uhpConfigured?'unavailable':'not_configured',configured:this.uhpConfigured,discovery,error:this.discoveryError},memory:{status:this.memoryServiceState,configured:this.memoryConfigured} }; }
  async refreshDiscovery() {
    if(!this.uhpConfigured||!this.uhp.discover){this.discoveryError=undefined;return;}
    try { this.discovery=await this.uhp.discover(true); this.discoveryError=undefined; await this.store.mutate(s=>{const configs:RoleConfig[]=this.discovery!.harnesses.flatMap(h=>[...(h.models??[]),...(this.discovery!.models??[]).filter(m=>(m as any).harnessId===h.id)].filter(m=>m.available!==false).map(m=>({harnessId:h.id,model:m.id})));for(const role of s.roles){role.availableConfigs=structuredClone(configs);role.enabled=configs.length>0;if(this.configuredRoleChoice&&configs.some(c=>c.harnessId===this.configuredRoleChoice!.harnessId&&c.model===this.configuredRoleChoice!.model)&&!role.config.harnessId)role.config=structuredClone(this.configuredRoleChoice);}s.events.push(event('uhp.discovery_updated','service','uhp',{version:this.discovery!.version,configCount:configs.length}));}); }
    catch(error){this.discovery=undefined;this.discoveryError=error instanceof Error?error.message:String(error);await this.store.mutate(s=>{for(const role of s.roles){role.enabled=false;role.availableConfigs=[];}s.events.push(event('uhp.discovery_failed','service','uhp',{error:this.discoveryError}));});}
  }

  async createProject(name: string): Promise<unknown> {
    const clean = name.trim(); if (!clean) throw new Error('Project name is required');
    const project=await this.store.mutate(s => { const defaults=Object.fromEntries(s.roles.filter(r=>r.config.harnessId&&r.config.model).map(r=>[r.id,structuredClone(r.config)]));const project = { id: id('prj'), name: clean, status: 'active' as const, defaultRoleConfigs: defaults, createdAt: now(), tasks: [] }; s.projects.push(project); s.events.push(event('project.created','project',project.id,{name:clean})); return project; });
    if(this.hindsight?.ensureBank)void this.hindsight.ensureBank((project as any).id).then(result=>this.memoryServiceState=result.status==='ready'?'ready':'degraded').catch(()=>this.memoryServiceState='degraded');
    return project;
  }
  async selectRoleConfig(roleId:string,config:RoleConfig,projectId?:string,runId?:string):Promise<unknown>{return this.store.mutate(s=>{const role=must(s.roles.find(r=>r.id===roleId),'Role');validateRoleConfig(role,config);if(runId){const run=this.findRun(s,runId);run.roleConfigs[roleId]=structuredClone(config);if(roleId==='planner'||roleId==='orchestrator'){const old=run.sessions[roleId];old.status='rotated';old.rotatedAt=now();run.sessionHistory.push(structuredClone(old));run.sessions[roleId]=newSession(roleId,config,old.generation+1);if(roleId==='planner')delete run.plannerSessionId;else delete run.orchestratorSessionId;}s.events.push(event('role_config.selected','run',runId,{roleId,config,scope:'run',sessionRotated:roleId==='planner'||roleId==='orchestrator'}));return run.roleConfigs[roleId];}if(projectId){const project=must(s.projects.find(p=>p.id===projectId),'Project');project.defaultRoleConfigs[roleId]=structuredClone(config);s.events.push(event('role_config.selected','project',projectId,{roleId,config,scope:'project'}));return project.defaultRoleConfigs[roleId];}role.config=structuredClone(config);s.events.push(event('role_config.selected','role',roleId,{config,scope:'global'}));return role.config;});}
  async createTask(projectId: string, title: string): Promise<unknown> {
    const clean = title.trim(); if (!clean) throw new Error('Task title is required');
    return this.store.mutate(s => { const p = must(s.projects.find(x=>x.id===projectId),'Project'); const task = { id:id('tsk'), title:clean, status:'ready' as const, createdAt:now(), runs:[] }; p.tasks.push(task); s.events.push(event('task.created','task',task.id,{projectId,title:clean})); return task; });
  }
  async createRun(taskId: string): Promise<unknown> {
    return this.store.mutate(s => { const {task}=this.findTask(s,taskId); const project=this.findProject(s,taskId); const roleConfigs=structuredClone(project.defaultRoleConfigs); for(const roleId of ['planner','orchestrator']) roleConfigs[roleId]??=structuredClone(must(s.roles.find(r=>r.id===roleId),'Role').config); const t=now(); const blank={harnessId:'',model:''};const run:Run = { id:id('run'), status:'planning', createdAt:t, sessions:{planner:newSession('planner',roleConfigs.planner??blank),orchestrator:newSession('orchestrator',roleConfigs.orchestrator??blank)}, sessionHistory:[], roleConfigs, guidance:[], assignments:[], reviews:[] }; task.status='active'; task.runs.push(run); s.events.push(event('run.created','run',run.id,{taskId,sessions:run.sessions})); return run; });
  }
  async rotateSession(runId:string,roleId:string):Promise<unknown>{if(roleId!=='planner'&&roleId!=='orchestrator')throw new Error('Only Planner and Orchestrator have long-lived sessions');return this.store.mutate(s=>{const run=this.findRun(s,runId),old=run.sessions[roleId],config=run.roleConfigs[roleId]??old.config;old.status='rotated';old.rotatedAt=now();run.sessionHistory.push(structuredClone(old));const session=newSession(roleId,config,old.generation+1);run.sessions[roleId]=session;if(roleId==='planner')delete run.plannerSessionId;else delete run.orchestratorSessionId;s.events.push(event('session.rotated','session',session.localId,{runId,roleId,generation:session.generation,previousLocalId:old.localId,previousUhpSessionId:old.uhpSessionId}));return session;});}
  async addGuidance(runId: string, text: string): Promise<unknown> {
    const clean=text.trim(); if(!clean) throw new Error('Guidance text is required');
    const guidance=await this.store.mutate(s=>{ const run=this.findRun(s,runId); const g: Guidance={id:id('guide'),sequence:Math.max(0,...run.guidance.map(x=>x.sequence))+1,text:clean,status:'queued',createdAt:now()}; run.guidance.push(g); run.status='waiting_guidance'; s.events.push(event('guidance.added','guidance',g.id,{runId,sequence:g.sequence,status:g.status,text:clean})); return g; });
    const run=this.findRun(await this.store.load(),runId);const role=run.roleConfigs.planner??(await this.store.load()).roles.find(r=>r.id==='planner')?.config;
    if(role?.harnessId&&role.model){try{const turn=await this.assign(runId,'planner',`Operator guidance (sequence ${guidance.sequence}):\n${clean}`,role);const text=typeof turn.result==='string'?turn.result:undefined;const saved=await this.store.mutate(s=>{const g=this.findRun(s,runId).guidance.find(x=>x.id===guidance.id)!;g.plannerAssignmentId=turn.id;g.plannerReply=text;s.events.push(event('planner.turn_completed','guidance',g.id,{assignmentId:turn.id,hasReply:!!text}));return g;});const latest=this.findRun(await this.store.load(),runId);if(!latest.assignments.some(a=>a.roleId==='worker'&&['submitting','submitted','running','cancel_requested'].includes(a.status)))try{await this.deliverGuidanceCheckpoint(runId);}catch{/* keep durable guidance queued when orchestration is not configured or handoff is unavailable */}return this.findRun(await this.store.load(),runId).guidance.find(g=>g.id===saved.id)!;}catch(error){await this.store.mutate(s=>{s.events.push(event('planner.turn_failed','guidance',guidance.id,{error:error instanceof Error?error.message:String(error)}));});}}
    else await this.store.mutate(s=>{s.events.push(event('planner.turn_unavailable','guidance',guidance.id,{reason:'No explicitly selected, discovered Planner configuration'}));});
    return this.findRun(await this.store.load(),runId).guidance.find(x=>x.id===guidance.id);
  }
  async acknowledgeGuidance(guidanceId: string, acknowledgment: 'applied'|'replan'|'waiting'): Promise<unknown> {
    if(!['applied','replan','waiting'].includes(acknowledgment)) throw new Error('Invalid guidance acknowledgment');
    return this.store.mutate(s=>{ const g=must(s.projects.flatMap(p=>p.tasks).flatMap(t=>t.runs).flatMap(r=>r.guidance).find(x=>x.id===guidanceId),'Guidance'); if(g.status!=='delivered')throw Object.assign(new Error('Guidance must reach a safe checkpoint before acknowledgment'),{statusCode:409});g.status=acknowledgment; g.acknowledgment=acknowledgment; g.acknowledgedAt=now();const run=this.findGuidanceRun(s,guidanceId);if(!run.guidance.some(x=>x.status==='queued'||x.status==='delivered'))run.status='planning';s.events.push(event('guidance.acknowledged','guidance',g.id,{acknowledgment}));return g; });
  }
  async deliverGuidanceCheckpoint(runId:string):Promise<Guidance[]>{
    const state=await this.store.load(),run=this.findRun(state,runId);
    if(run.assignments.some(a=>['submitting','submitted','running','cancel_requested'].includes(a.status)))throw Object.assign(new Error('Guidance can only be handed off when all assignments have reached a safe checkpoint'),{statusCode:409});
    const queued=run.guidance.filter(g=>g.status==='queued').sort((a,b)=>a.sequence-b.sequence);if(!queued.length)return [];
    const role=run.roleConfigs.orchestrator??state.roles.find(r=>r.id==='orchestrator')?.config;if(!role?.harnessId||!role.model)throw Object.assign(new Error('No explicitly selected, discovered Orchestrator configuration'),{statusCode:409});
    const ids=queued.map(g=>g.id),handoff=queued.map(g=>`${g.id} | ${g.sequence}. ${g.text}`).join('\n');const plannerNotes=run.assignments.filter(a=>a.roleId==='planner'&&a.status==='succeeded').map(a=>typeof a.result==='string'?a.result:JSON.stringify(a.result)).join('\n').slice(0,6000);
    const prompt=`Safe-checkpoint handoff. Review the guidance in order. Return exactly one JSON object and no prose: {"acknowledgments":[{"guidanceId":"...","action":"applied|replan|waiting","reason":"..."}]}. Include every supplied guidanceId exactly once. Use applied only if your orchestration state confirms it was applied; use replan if the plan must change; otherwise use waiting.\n\nPlanner context:\n${plannerNotes||'No Planner response recorded.'}\n\nOrdered guidance (IDs are authoritative):\n${handoff}`;
    const orchestration=await this.assign(runId,'orchestrator',prompt,role);
    const parsed=parseGuidanceAcknowledgments(orchestration.result,ids);
    return this.store.mutate(s=>{const current=this.findRun(s,runId),byId=new Map(parsed?.map(x=>[x.guidanceId,x]));for(const g of current.guidance.filter(g=>g.status==='queued')){g.status='delivered';g.checkpointHandoffAssignmentId=orchestration.id;s.events.push(event('guidance.delivered','guidance',g.id,{runId,sequence:g.sequence,orchestratorAssignmentId:orchestration.id}));const ack=byId.get(g.id);if(ack){g.status=ack.action;g.acknowledgment=ack.action;g.acknowledgedAt=now();s.events.push(event('guidance.acknowledged','guidance',g.id,{acknowledgment:ack.action,reason:ack.reason,source:'orchestrator',assignmentId:orchestration.id}));}}if(!parsed)s.events.push(event('guidance.handoff_invalid','run',runId,{assignmentId:orchestration.id,reason:'Orchestrator response did not contain a valid complete JSON acknowledgment envelope'}));if(!current.guidance.some(g=>g.status==='queued'||g.status==='delivered'))current.status='planning';return current.guidance.filter(g=>g.checkpointHandoffAssignmentId===orchestration.id);});
  }
  async assign(runId: string, roleId: string, prompt: string, config?: RoleConfig): Promise<Assignment> {
    const submissionId=id('sub'), assignmentId=id('asgn'), key=id('idem');
    const prep = await this.store.mutate(s=>{ const {project,task,run}=this.findRunContext(s,runId); const role=must(s.roles.find(x=>x.id===roleId),'Role'); const requested=config ?? run.roleConfigs[roleId] ?? project.defaultRoleConfigs[roleId] ?? role.config; validateRoleConfig(role,requested); if(!prompt.trim()) throw new Error('Assignment prompt is required');if(this.verifiedWorkspaceConfig&&run.approval)throw Object.assign(new Error('No assignments are allowed after the human decision; retry in a new run'),{statusCode:409});if(roleId==='worker'&&this.verifiedWorkspaceConfig){if(!run.pinnedBaseCommit||(this.verifiedWorkspaceConfig.bridgeBaseUrl&&!run.workspaceId))throw Object.assign(new Error('Pin a base and prepare the Worker workspace before submission'),{statusCode:409});if(run.assignments.some(a=>a.roleId==='worker'))throw Object.assign(new Error('A verified workflow permits one Worker assignment per run; retry in a new run'),{statusCode:409});}if(roleId==='reviewer'){const old=run.assignments.some(a=>a.roleId==='reviewer'&&['submitting','submitted','running','cancel_requested'].includes(a.status))||run.assignments.some(a=>a.roleId==='reviewer'&&a.status==='succeeded'&&!run.reviewerRetryAuthorized);if(!run.workerEvidence?.scopeVerified||run.validation?.status!=='passed'||run.reviewerRecommendation||old||prompt.trim()!==this.reviewerPrompt(run)||JSON.stringify(requested)!==JSON.stringify(run.roleConfigs.reviewer??project.defaultRoleConfigs.reviewer??role.config)||requested.options?.workspace_id!==undefined)throw Object.assign(new Error('Reviewer submission must use the controller evidence prompt and selected read-only Reviewer configuration'),{statusCode:409});run.reviewerRetryAuthorized=false;}const a: Assignment={id:assignmentId,roleId,status:'submitting',requestedConfig:structuredClone(requested),prompt:prompt.trim(),submissionId,idempotencyKey:key,createdAt:now()}; run.assignments.push(a); if(roleId==='worker')run.status='running';else if(!run.guidance.some(g=>g.status==='queued'||g.status==='delivered'))run.status=roleId==='reviewer'?'review':'planning';s.events.push(event('assignment.submission_intent','assignment',a.id,{runId,roleId,submissionId,idempotencyKey:key,requestedConfig:requested}));return {a,project,task,run}; });
    return this.submitExisting(prep.project.id,prep.task.id,prep.run.id,prep.a.id);
  }
  async recover(): Promise<void> {
    const s=await this.store.load();
    for (const p of s.projects) for(const t of p.tasks) for(const r of t.runs) for(const a of r.assignments) {
      if(a.status==='cancel_requested') { if(a.externalId) { await this.dispatchCancel(a).catch(()=>undefined);const latest=this.findAssignment(await this.store.load(),a.id).a;if(latest.status==='cancel_requested'&&latest.responseId)await this.reconcileExisting(a.id).catch(()=>undefined); } else await this.submitExisting(p.id,t.id,r.id,a.id,true).catch(()=>undefined); }
      else if(a.status==='submitting'||a.status==='running') { if(a.responseId&&this.uhp.retrieve) await this.reconcileExisting(a.id).catch(()=>undefined); else if(a.status==='submitting') await this.submitExisting(p.id,t.id,r.id,a.id,true).catch(()=>undefined); }
    }
    if(this.verifiedWorkspaceConfig){let latest=await this.store.load();for(const p of latest.projects)for(const t of p.tasks)for(const r of t.runs)if(r.workerEvidence&&!r.validation)await this.retryValidation(r.id).catch(()=>undefined);latest=await this.store.load();for(const p of latest.projects)for(const t of p.tasks)for(const r of t.runs)if(r.workerEvidence&&r.validation?.status==='passed'&&!r.reviewerRecommendation){const reviewer=r.assignments.filter(a=>a.roleId==='reviewer'&&a.status==='succeeded').at(-1);if(reviewer)await this.recordReviewerRecommendation(r.id,reviewer.id,r.workerEvidence.provenance==='recorded_replay'?'simulated_fixture':'uhp_response').catch(()=>undefined);}}
    await this.resumePendingRetentions();
  }
  async reconcileRunning():Promise<void>{const s=await this.store.load();for(const p of s.projects)for(const t of p.tasks)for(const r of t.runs)for(const a of r.assignments)if((a.status==='running'||a.status==='cancel_requested')&&a.responseId)await this.reconcileExisting(a.id).catch(()=>undefined);}
  async refreshAssignment(assignmentId:string):Promise<unknown>{return this.reconcileExisting(assignmentId).then(async()=>this.findAssignment(await this.store.load(),assignmentId).a);}
  private async reconcileExisting(assignmentId:string):Promise<void>{const snapshot=await this.store.load(),{a}=this.findAssignment(snapshot,assignmentId);if(!a.responseId||!this.uhp.retrieve)return;const response=await this.uhp.retrieve(a.responseId);const terminal=normalizeStatus(response.status);if(['succeeded','failed','needs_revision','cancelled'].includes(terminal)){await this.store.mutate(s=>{const {a:r,run}=this.findAssignment(s,assignmentId);const wasCancelRequested=r.status==='cancel_requested';r.status=terminal;if(wasCancelRequested&&terminal!=='cancelled')s.events.push(event('assignment.cancel_raced_terminal','assignment',r.id,{status:terminal,source:'reconciled-response'}));r.result=response.output_text??response.output??response.error;r.externalId=response.id;const meta=response.metadata??{};if(typeof meta.session_id==='string')r.sessionId=meta.session_id;if(typeof response.model==='string'&&typeof meta.harness_id==='string'){r.actualConfig={harnessId:meta.harness_id,model:response.model};r.configOutcome=r.actualConfig.model===r.requestedConfig.model&&r.actualConfig.harnessId===r.requestedConfig.harnessId?'confirmed':'substituted';}if(response.usage&&typeof response.usage==='object'){const u=response.usage,usage:Usage={measured:true};const copy=(source:unknown,target:'inputTokens'|'outputTokens'|'totalTokens'|'cachedInputTokens'|'requestCount')=>{if(typeof source==='number'&&Number.isFinite(source))usage[target]=source;};copy(u.input_tokens,'inputTokens');copy(u.output_tokens,'outputTokens');copy(u.total_tokens,'totalTokens');copy(u.input_tokens_details?.cached_tokens??u.cached_input_tokens,'cachedInputTokens');copy(u.request_count??u.requests,'requestCount');if(Object.keys(usage).length>1)r.usage={...r.usage,...usage};}if(r.roleId==='planner'||r.roleId==='orchestrator'){const session=run.sessions[r.roleId];session.responseId=response.id;if(r.sessionId)session.uhpSessionId=r.sessionId;if(r.roleId==='planner')run.plannerSessionId=session.uhpSessionId;else run.orchestratorSessionId=session.uhpSessionId;}s.events.push(event('assignment.reconciled','assignment',r.id,{responseId:r.responseId,status:terminal}));});}else await this.store.mutate(s=>{const {a:r}=this.findAssignment(s,assignmentId);if(r.status!=='cancel_requested')r.status='running';s.events.push(event('assignment.reconciled','assignment',r.id,{responseId:r.responseId,status:response.status}));});}
  private async submitExisting(projectId:string,taskId:string,runId:string,assignmentId:string,retrying=false): Promise<Assignment> {
    const snapshot=await this.store.load(); const {a}=this.findAssignment(snapshot,assignmentId); if(a.status!=='submitting'&&a.status!=='cancel_requested') return a;
    if(retrying&&this.discovery&&this.discovery.capabilities.idempotency!==true){await this.store.mutate(s=>{s.events.push(event('assignment.recovery_blocked','assignment',assignmentId,{reason:'UHP idempotency is unavailable; controller will not repeat the submission'}));});return a;}
    try {
      const context=await this.store.load();const {run}=this.findAssignment(context,assignmentId);const uhpSession=a.roleId==='planner'||a.roleId==='orchestrator'?run.sessions[a.roleId]:undefined;const config={...(a.requestedConfig.options??{}),...a.requestedConfig,timeoutSeconds:(a.requestedConfig.options?.timeoutSeconds??this.taskTimeoutSeconds),...(a.roleId==='worker'&&run.workspaceId?{workspaceId:run.workspaceId}:{}),...(uhpSession&&uhpSession.responseId?{previousResponseId:uhpSession.responseId}:{})};
      let prompt=a.prompt; if(this.hindsight){const memory=await this.hindsight.recall(projectId,a.prompt);this.memoryServiceState=memory.status==='ready'?'ready':'degraded';if(memory.memories.length)prompt=`Relevant project memory (reference only):\n${memory.memories.map(x=>x.text.slice(0,1200)).join('\n---\n').slice(0,6000)}\n\nCurrent assignment:\n${a.prompt}`;await this.store.mutate(s=>{s.events.push(event('memory.recall','project',projectId,{status:memory.status,bankId:memory.bankId,count:memory.memories.length,...(memory.error?{error:memory.error}:{})}));});}
      const response=await this.uhp.submit({submissionId:a.submissionId,assignmentId:a.id,runId,roleId:a.roleId,taskId,projectId,prompt,config,idempotencyKey:a.idempotencyKey,onEvent:async progress=>{let cancel:Assignment|undefined;await this.store.mutate(s=>{const {a:r,run}=this.findAssignment(s,assignmentId);if(progress.responseId){r.externalId??=progress.responseId;r.responseId??=progress.responseId;if(r.status!=='cancel_requested'&&r.status!=='cancelled')r.status='running';if(r.status==='cancel_requested')cancel=structuredClone(r);}if(progress.sessionId)r.sessionId=progress.sessionId;if(r.roleId==='planner'||r.roleId==='orchestrator'){const session=run.sessions[r.roleId];if(progress.responseId)session.responseId=progress.responseId;if(progress.sessionId){session.uhpSessionId=progress.sessionId;session.status='active';if(r.roleId==='planner')run.plannerSessionId=progress.sessionId;else run.orchestratorSessionId=progress.sessionId;}}s.events.push(event('assignment.progress','assignment',r.id,{type:progress.type,responseId:progress.responseId,sessionId:progress.sessionId,providerEvent:progress.event}));});if(cancel)await this.dispatchCancel(cancel);}});
      return this.store.mutate(s=>{const {a:r,run}=this.findAssignment(s,assignmentId); r.externalId=response.externalId; r.responseId=response.responseId; r.sessionId=response.sessionId; if(response.actualModel&&response.selectedHarnessId)r.actualConfig={harnessId:response.selectedHarnessId,model:response.actualModel};r.configOutcome=r.actualConfig?((response.modelFallback||response.actualModel!==r.requestedConfig.model||response.selectedHarnessId!==r.requestedConfig.harnessId)?'substituted':'confirmed'):'unavailable';r.configNotes={...(response.boundsApplied!==undefined?{boundsApplied:response.boundsApplied}:{}),...(response.ignoredFields?.length?{ignoredFields:[...response.ignoredFields]}:{})};if(response.usage&&Object.keys(response.usage).length)r.usage={...response.usage,measured:true,...(response.runtimeMs!==undefined?{runtimeMs:response.runtimeMs}:{})};else if(response.runtimeMs!==undefined)r.usage={runtimeMs:response.runtimeMs,measured:true};const terminal=normalizeStatus(response.status);if(r.status==='cancel_requested'&&['succeeded','failed','needs_revision','cancelled'].includes(terminal)){r.status=terminal;if(terminal!=='cancelled')s.events.push(event('assignment.cancel_raced_terminal','assignment',r.id,{status:terminal,source:'submit-terminal'}));}else if(r.status!=='cancelled')r.status=terminal;r.result=response.output ?? response.outputText ?? response.result;if(r.roleId==='planner'||r.roleId==='orchestrator'){const session=run.sessions[r.roleId];session.responseId=response.responseId??response.externalId;if(response.sessionId)session.uhpSessionId=response.sessionId;session.status='active';if(r.roleId==='planner')run.plannerSessionId=session.uhpSessionId;else run.orchestratorSessionId=session.uhpSessionId;}const pendingGuidance=run.guidance.some(g=>g.status==='queued'||g.status==='delivered');const workerActive=run.assignments.some(a=>a.id!==r.id&&a.roleId==='worker'&&['submitting','submitted','running','cancel_requested'].includes(a.status));run.status=r.status==='failed'?'failed':r.status==='needs_revision'?'review':pendingGuidance?'waiting_guidance':r.roleId==='worker'&&r.status==='succeeded'?'review':r.roleId==='reviewer'?'review':workerActive?'running':'planning';s.events.push(event('assignment.submitted','assignment',r.id,{submissionId:r.submissionId,externalId:r.externalId,responseId:r.responseId,sessionId:r.sessionId,status:r.status,requestedConfig:r.requestedConfig,actualConfig:r.actualConfig,configOutcome:r.configOutcome,usage:r.usage}));return r;});
    } catch(error) { await this.store.mutate(s=>{const {a:r}=this.findAssignment(s,assignmentId); r.error=error instanceof Error?error.message:String(error); s.events.push(event('assignment.submit_uncertain','assignment',r.id,{error:r.error,idempotencyKey:r.idempotencyKey}));}); throw error; }
  }
  async cancelAssignment(assignmentId:string): Promise<unknown> {
    const item=await this.store.mutate(s=>{const {a}=this.findAssignment(s,assignmentId); if(['cancelled','succeeded','failed'].includes(a.status)) return a; a.status='cancel_requested'; a.cancelIdempotencyKey ??= id('idem-cancel'); s.events.push(event('assignment.cancel_intent','assignment',a.id,{idempotencyKey:a.cancelIdempotencyKey})); return a;});
    if(item.status!=='cancel_requested') return item;
    if(!item.externalId)return item;
    return this.dispatchCancel(item);
  }
  private async dispatchCancel(item:Assignment):Promise<Assignment>{const current=this.cancellationInFlight.get(item.id);if(current)return current as Promise<Assignment>;const work=(async()=>{const idempotencyKey=item.cancelIdempotencyKey??`cancel-${item.submissionId}`;try{await this.store.mutate(s=>{const {a}=this.findAssignment(s,item.id);a.cancelIdempotencyKey??=idempotencyKey;});const response=await this.uhp.cancel({submissionId:item.submissionId,externalId:item.externalId,idempotencyKey});return await this.store.mutate(s=>{const {a,run}=this.findAssignment(s,item.id);const terminal=normalizeStatus(response.status);if(a.status==='cancel_requested'){if(response.status==='cancelled')a.status='cancelled';else if(['succeeded','failed','needs_revision'].includes(terminal)){a.status=terminal;s.events.push(event('assignment.cancel_raced_terminal','assignment',a.id,{status:terminal,source:'cancel-response'}));}}if(a.status==='cancelled'&&run.guidance.some(g=>g.status==='queued'))run.status='waiting_guidance';s.events.push(event('assignment.cancel_result','assignment',a.id,{status:response.status,idempotencyKey:a.cancelIdempotencyKey}));return a;});}catch(error){await this.store.mutate(s=>{const {a}=this.findAssignment(s,item.id);s.events.push(event('assignment.cancel_error','assignment',a.id,{error:error instanceof Error?error.message:String(error),idempotencyKey:a.cancelIdempotencyKey}));}).catch(()=>undefined);return this.findAssignment(await this.store.load(),item.id).a;}finally{this.cancellationInFlight.delete(item.id);}})();this.cancellationInFlight.set(item.id,work);return work;}
  /** Verify an externally supplied bridge snapshot against the configured pinned base and scope, then run controller-owned checks. */
  async verifyWorkerOutput(runId:string,workerAssignmentId:string):Promise<unknown>{const config=this.verifiedWorkspaceConfig;if(!config?.bridgeBaseUrl)throw Object.assign(new Error('Workspace bridge URL is not configured'),{statusCode:503});const {run}=this.findAssignment(await this.store.load(),workerAssignmentId),worker=must(run.assignments.find(a=>a.id===workerAssignmentId),'Worker assignment');if(run.id!==runId||!run.workspaceId||!run.pinnedBaseCommit||!worker.responseId||worker.status!=='succeeded'||!this.uhp.retrieve)throw Object.assign(new Error('Completed Worker response with a pinned bridge workspace and response retrieval are required'),{statusCode:409});const response=await this.uhp.retrieve(worker.responseId);if(response.id!==worker.responseId||!['completed','succeeded'].includes(response.status)||response.metadata?.workspace_id!==run.workspaceId)throw Object.assign(new Error('Retrieved Worker response does not prove the completed pinned workspace binding'),{statusCode:409});if(typeof response.model==='string'&&worker.actualConfig?.model&&response.model!==worker.actualConfig.model)throw Object.assign(new Error('Retrieved actual model conflicts with the saved Worker response'),{statusCode:409});await this.store.mutate(s=>{const a=this.findAssignment(s,worker.id).a;if(typeof response.model==='string')a.actualConfig={harnessId:String(response.metadata?.harness_id??a.actualConfig?.harnessId??a.requestedConfig.harnessId),model:response.model};if(response.usage){const u=response.usage,usage:Usage={measured:true};const put=(value:unknown,key:'inputTokens'|'outputTokens'|'totalTokens'|'cachedInputTokens'|'requestCount')=>{if(typeof value==='number'&&Number.isFinite(value))usage[key]=value;};put(u.input_tokens,'inputTokens');put(u.output_tokens,'outputTokens');put(u.total_tokens,'totalTokens');put(u.input_tokens_details?.cached_tokens??u.cached_input_tokens,'cachedInputTokens');put(u.request_count??u.requests,'requestCount');if(Object.keys(usage).length>1)a.usage={...a.usage,...usage};}});const envelope=await fetchBridgeSnapshot(config.bridgeBaseUrl,run.workspaceId,run.pinnedBaseCommit);return this.processWorkerOutput(runId,workerAssignmentId,envelope,'bridge_snapshot');}
  /** Deterministic fixture path. Never exposed by the production HTTP API. */
  async replayRecordedWorkerOutput(runId:string,workerAssignmentId:string,recordedEvidence:unknown):Promise<unknown>{return this.processWorkerOutput(runId,workerAssignmentId,recordedEvidence,'recorded_replay');}
  private async processWorkerOutput(runId:string,workerAssignmentId:string,envelope:unknown,provenance:'bridge_snapshot'|'recorded_replay'):Promise<unknown>{
    const config=this.verifiedWorkspaceConfig;if(!config)throw Object.assign(new Error('Verified workspace workflow is not configured'),{statusCode:503});
    const {run}=this.findAssignment(await this.store.load(),workerAssignmentId),worker=must(run.assignments.find(a=>a.id===workerAssignmentId),'Worker assignment');
    if(run.id!==runId||worker.roleId!=='worker'||worker.status!=='succeeded'||!worker.responseId)throw Object.assign(new Error('A completed Worker response is required'),{statusCode:409});
    if(run.workerEvidence){if(run.workerEvidence.workerAssignmentId===worker.id&&run.workerEvidence.responseId===worker.responseId)return {workerEvidence:run.workerEvidence,validation:run.validation};throw Object.assign(new Error('This run already has verified Worker evidence'),{statusCode:409});}
    const pinnedBaseCommit=run.pinnedBaseCommit;
    if(!pinnedBaseCommit||(envelope as any)?.base_commit?.toLowerCase?.()!==pinnedBaseCommit.toLowerCase()&&(envelope as any)?.baseCommit?.toLowerCase?.()!==pinnedBaseCommit.toLowerCase())throw Object.assign(new Error('Snapshot base does not match the run pinned base'),{statusCode:409});
    if(provenance==='recorded_replay'){const recorded=envelope as any;if(recorded.responseId!==worker.responseId)throw Object.assign(new Error('Recorded Worker response ID does not match the assignment'),{statusCode:409});if(recorded.sessionId!==undefined&&worker.sessionId!==undefined&&recorded.sessionId!==worker.sessionId)throw Object.assign(new Error('Recorded Worker session ID does not match the assignment'),{statusCode:409});if(recorded.actualModel!==undefined&&recorded.actualModel!==worker.actualConfig?.model)throw Object.assign(new Error('Recorded actual model does not match the assignment evidence'),{statusCode:409});if(recorded.usage!==undefined){const raw=recorded.usage as Record<string,unknown>,measured={inputTokens:raw.inputTokens??raw.input_tokens,outputTokens:raw.outputTokens??raw.output_tokens,totalTokens:raw.totalTokens??raw.total_tokens,cachedInputTokens:raw.cachedInputTokens??raw.cached_input_tokens??(raw.input_tokens_details as any)?.cached_tokens,requestCount:raw.requestCount??raw.request_count};const normalized=Object.fromEntries(Object.entries(measured).filter(([,v])=>v!==undefined));if(!worker.usage||Object.entries(normalized).some(([k,v])=>worker.usage?.[k as keyof Usage]!==v))throw Object.assign(new Error('Recorded measured usage does not match the assignment evidence'),{statusCode:409});}}
    try {
      const verified:VerifiedWorkerWorkspace=provenance==='bridge_snapshot'
        ?await verifyWorkerSnapshot({repoPath:config.repoPath,pinnedBaseCommit,envelope:envelope as any,allowedScope:config.allowedScope})
        :await reconstructRecordedSnapshot({repoPath:config.repoPath,pinnedBaseCommit,recordedEvidence:envelope as any,allowedScope:config.allowedScope});
      const evidence:WorkerEvidence={...verified,workerAssignmentId:worker.id,responseId:worker.responseId,...(worker.actualConfig?.model?{actualModel:worker.actualConfig.model}:{}),...(worker.usage?{usage:structuredClone(worker.usage)}:{}),acceptance:'not_decided'};
      await this.store.mutate(s=>{const r=this.findRun(s,runId);if(r.workerEvidence)throw Object.assign(new Error('Worker evidence was already recorded'),{statusCode:409});r.workerEvidence=evidence;r.status='validation';s.events.push(event('worker.evidence_verified','run',runId,{workerAssignmentId:worker.id,responseId:worker.responseId,actualModel:evidence.actualModel,usage:evidence.usage,pinnedBaseCommit:evidence.pinnedBaseCommit,completeSnapshot:evidence.completeSnapshot,scopeVerified:true,provenance}));});
      const observed=await validateWorkerOutput({repoPath:config.repoPath,evidence:verified,commands:config.commands,timeoutMs:config.timeoutMs,maxOutputBytes:config.maxOutputBytes});
      const checks:ValidationCheck[]=(observed.checks??[]).map(c=>({...c,passed:c.exitCode===0&&!c.timedOut&&!c.outputTruncated}));
      const passed=observed.passed===true&&checks.length===config.commands.length&&checks.every(c=>c.passed);
      const record={id:id('valid'),status:passed?'passed' as const:'failed' as const,passed,reportedPassed:passed,checks:checks.map(c=>({name:c.name,passed:c.passed,details:c.output})),observations:checks,policy:{requireAllChecksPass:true as const,configuredCheckCount:config.commands.length},gitEvidence:{status:'verified' as const,commit:evidence.pinnedBaseCommit,changedPaths:evidence.changes.map(c=>c.path),submittedAt:now()},createdAt:now()};
      await this.store.mutate(s=>{const r=this.findRun(s,runId);r.validation=record;r.status=passed?'review':'failed';s.events.push(event('validation.observed','run',runId,{validationId:record.id,passed,policy:record.policy,observations:checks}));});
      return {workerEvidence:evidence,validation:record};
    } catch(error) {await this.store.mutate(s=>{const r=this.findRun(s,runId);r.status='failed';s.events.push(event('worker.evidence_rejected','run',runId,{workerAssignmentId,error:error instanceof Error?error.message:String(error)}));});throw error;}
  }
  async retryValidation(runId:string):Promise<unknown>{const config=this.verifiedWorkspaceConfig;if(!config)throw Object.assign(new Error('Verified workspace workflow is not configured'),{statusCode:503});const run=this.findRun(await this.store.load(),runId);if(!run.workerEvidence||!run.workerEvidence.scopeVerified)throw Object.assign(new Error('Verified Worker evidence is required before validation'),{statusCode:409});if(run.validation?.passed)throw Object.assign(new Error('Validation already passed'),{statusCode:409});const verified:VerifiedWorkerWorkspace={...run.workerEvidence};const observed=await validateWorkerOutput({repoPath:config.repoPath,evidence:verified,commands:config.commands,timeoutMs:config.timeoutMs,maxOutputBytes:config.maxOutputBytes});const checks:ValidationCheck[]=(observed.checks??[]).map(c=>({...c,passed:c.exitCode===0&&!c.timedOut&&!c.outputTruncated})),passed=observed.passed===true&&checks.length===config.commands.length&&checks.every(c=>c.passed);const record={id:id('valid'),status:passed?'passed' as const:'failed' as const,passed,reportedPassed:passed,checks:checks.map(c=>({name:c.name,passed:c.passed,details:c.output})),observations:checks,policy:{requireAllChecksPass:true as const,configuredCheckCount:config.commands.length},gitEvidence:{status:'verified' as const,commit:run.workerEvidence.pinnedBaseCommit,changedPaths:run.workerEvidence.changes.map(c=>c.path),submittedAt:now()},createdAt:now()};await this.store.mutate(s=>{const r=this.findRun(s,runId);r.validation=record;r.status=passed?'review':'failed';s.events.push(event('validation.retry_observed','run',runId,{validationId:record.id,passed,observations:checks}));});return record;}
  async requestReviewer(runId:string,provenance:'uhp_response'|'simulated_fixture'='uhp_response'):Promise<unknown>{const state=await this.store.load(),run=this.findRun(state,runId);if(!run.workerEvidence?.scopeVerified||run.validation?.status!=='passed')throw Object.assign(new Error('Verified Worker scope and successful controller validation are required before Reviewer submission'),{statusCode:409});if(run.reviewerRecommendation)throw Object.assign(new Error('Reviewer recommendation already exists'),{statusCode:409});if(run.assignments.some(a=>a.roleId==='reviewer'&&['submitting','submitted','running','cancel_requested'].includes(a.status))||run.assignments.some(a=>a.roleId==='reviewer'&&a.status==='succeeded'&&!run.reviewerRetryAuthorized))throw Object.assign(new Error('Reviewer submission is already active or complete; use the explicit retry path'),{statusCode:409});const config=run.roleConfigs.reviewer??state.roles.find(r=>r.id==='reviewer')?.config;if(!config?.harnessId||!config.model)throw Object.assign(new Error('No explicitly selected Reviewer configuration'),{statusCode:409});const assignment=await this.assign(runId,'reviewer',this.reviewerPrompt(run),config);return assignment.status==='succeeded'?this.recordReviewerRecommendation(runId,assignment.id,provenance):assignment;}
  private reviewerPrompt(run:Run):string {if(!run.workerEvidence||!run.validation)throw new Error('Verified Worker evidence and validation observations are required');return `Review this exact controller-verified Worker diff and validation evidence. Return one JSON object only: {"verdict":"recommend|request_changes|reject","rationale":"..."}. Your response cannot approve or change files.\n\nDIFF:\n${run.workerEvidence.reviewDiff}\n\nCONTROLLER-OBSERVED VALIDATION:\n${JSON.stringify(run.validation.observations,null,2)}\n\nPinned base: ${run.workerEvidence.pinnedBaseCommit}\nScope verified: true\nValidation policy passed: true`;}
  async retryReviewer(runId:string):Promise<void>{await this.store.mutate(s=>{const run=this.findRun(s,runId);if(!run.reviewerRecommendation||run.reviewerRecommendation.verdict==='recommend')throw Object.assign(new Error('Only a non-recommending Reviewer result can be explicitly retried'),{statusCode:409});if(run.approval)throw Object.assign(new Error('A human decision is final for this run'),{statusCode:409});const previous=run.reviewerRecommendation;delete run.reviewerRecommendation;run.reviewerRetryAuthorized=true;run.status='review';s.events.push(event('reviewer.retry_authorized','run',runId,{previousRecommendationId:previous.id}));});}
  async recordReviewerRecommendation(runId:string,reviewerAssignmentId:string,provenance:'uhp_response'|'simulated_fixture'='uhp_response'):Promise<unknown>{return this.store.mutate(s=>{const run=this.findRun(s,runId),reviewer=must(run.assignments.find(a=>a.id===reviewerAssignmentId),'Reviewer assignment');if(!run.workerEvidence?.scopeVerified||run.validation?.status!=='passed')throw Object.assign(new Error('Verified Worker evidence and passing validation are required'),{statusCode:409});if((provenance==='simulated_fixture')!==(run.workerEvidence.provenance==='recorded_replay'))throw Object.assign(new Error('Reviewer provenance must match the Worker evidence source'),{statusCode:409});if(reviewer.roleId!=='reviewer'||reviewer.status!=='succeeded'||!reviewer.responseId)throw Object.assign(new Error('Reviewer response must be completed'),{statusCode:409});if(run.reviewerRecommendation)throw Object.assign(new Error('Reviewer recommendation already recorded'),{statusCode:409});const raw=typeof reviewer.result==='string'?reviewer.result:JSON.stringify(reviewer.result??'');let parsed:unknown;try{parsed=JSON.parse(raw);}catch{}const value=parsed&&typeof parsed==='object'?parsed as Record<string,unknown>:{};let verdict:'recommend'|'request_changes'|'reject'|'unparsed'=['recommend','request_changes','reject'].includes(String(value.verdict))?value.verdict as 'recommend'|'request_changes'|'reject':'unparsed';const rationale=(typeof value.rationale==='string'?value.rationale:raw).trim().slice(0,4000);if(!rationale)verdict='unparsed';const recommendation={id:id('recommendation'),status:'proposed' as const,provenance,reviewerAssignmentId:reviewer.id,harnessId:reviewer.actualConfig?.harnessId??reviewer.requestedConfig.harnessId,model:reviewer.requestedConfig.model,...(reviewer.actualConfig?.model?{actualModel:reviewer.actualConfig.model}:{}),responseId:reviewer.responseId,verdict,rationale,createdAt:now()};run.reviewerRecommendation=recommendation;run.reviewerRecommendationHistory??=[];run.reviewerRecommendationHistory.push(structuredClone(recommendation));run.status='awaiting_approval';s.events.push(event('reviewer.recommendation_recorded','run',runId,{recommendationId:recommendation.id,reviewerAssignmentId:reviewer.id,responseId:reviewer.responseId,harnessId:recommendation.harnessId,model:recommendation.model,actualModel:recommendation.actualModel,verdict,provenance}));return recommendation;});}
  async addReview(runId:string,input:{reviewerAssignmentId:string;implementationAssignmentIds:string[];verdict:'clear'|'changes_requested'|'rejected';scope:string[];summary:string}):Promise<unknown>{return this.store.mutate(s=>{const run=this.findRun(s,runId),reviewer=must(run.assignments.find(a=>a.id===input.reviewerAssignmentId),'Reviewer assignment');if(reviewer.roleId!=='reviewer'||reviewer.status!=='succeeded')throw new Error('Reviewer proposal requires a completed Reviewer assignment');if(!input.implementationAssignmentIds.length||input.implementationAssignmentIds.includes(reviewer.id))throw new Error('Reviewer cannot approve its own implementation');for(const assignmentId of input.implementationAssignmentIds){const impl=must(run.assignments.find(a=>a.id===assignmentId),'Implementation assignment');if(impl.roleId!=='worker'||impl.status!=='succeeded')throw new Error('Review scope must contain completed Worker assignments');}const implemented=run.assignments.filter(a=>a.roleId==='worker'&&a.status==='succeeded').map(a=>a.id).sort();if(JSON.stringify(implemented)!==JSON.stringify([...input.implementationAssignmentIds].sort()))throw new Error('Reviewer proposal must cover every completed Worker assignment');if(!['clear','changes_requested','rejected'].includes(input.verdict)||!input.scope.length)throw new Error('Review verdict and scope are required');const review={id:id('review'),status:'proposed' as const,reviewerAssignmentId:reviewer.id,implementationAssignmentIds:[...input.implementationAssignmentIds],verdict:input.verdict,scope:input.scope.map(x=>x.trim()).filter(Boolean),summary:input.summary.trim(),createdAt:now()};run.reviews.push(review);run.status='review';s.events.push(event('review.proposed','review',review.id,{runId,verdict:review.verdict,implementationAssignmentIds:review.implementationAssignmentIds,authority:'unverified-agent-proposal'}));return review;});}
  async recordValidation(runId:string,input:{passed:boolean;checks:Array<{name:string;passed:boolean;details?:string}>;gitEvidence?:{commit?:string;tree?:string;changedPaths?:string[]}}):Promise<unknown>{return this.store.mutate(s=>{const run=this.findRun(s,runId);if(run.workerEvidence||run.validation?.observations)throw Object.assign(new Error('Client-reported validation cannot overwrite controller-observed evidence'),{statusCode:409});if(!run.reviews.some(r=>r.status==='verified'&&r.verdict==='clear'))throw Object.assign(new Error('A controller-verified clear reviewer verdict is required before validation'),{statusCode:409});if(!Array.isArray(input.checks)||!input.checks.length||input.checks.some(c=>!c.name||typeof c.passed!=='boolean'))throw new Error('Validation requires named check results');const checks=structuredClone(input.checks),reportedPassed=input.passed&&checks.every(c=>c.passed);const record={id:id('valid'),status:'unverified' as const,passed:false,reportedPassed,checks,createdAt:now(),...(input.gitEvidence?{gitEvidence:{status:'unverified' as const,...input.gitEvidence,submittedAt:now()}}:{})};run.validation=record;run.status='validation';s.events.push(event('validation.reported','validation',record.id,{runId,reportedPassed,authority:'unverified-client-report',gitEvidenceStatus:record.gitEvidence?.status??'missing'}));return record;});}
  async approveRun(runId:string,input:{approved:boolean;evidenceCommit?:string;rationale?:string}):Promise<unknown>{
    const approval=await this.store.mutate(s=>{
      const context=this.findRunContext(s,runId),run=context.run;
      if(typeof input.approved!=='boolean')throw Object.assign(new Error('An explicit human approval or rejection decision is required'),{statusCode:400});
      if(run.approval)throw Object.assign(new Error('A human decision is final for this run'),{statusCode:409});
      if(!run.workerEvidence?.scopeVerified||run.workerEvidence.acceptance!=='not_decided'||!run.validation||run.validation.status!=='passed'||!run.validation.observations?.length||!run.reviewerRecommendation)throw Object.assign(new Error('Human decision requires verified Worker scope, passing controller-observed validation, and a recorded independent Reviewer recommendation'),{statusCode:409});
      const completedWorkers=run.assignments.filter(a=>a.roleId==='worker'&&a.status==='succeeded');
      if(!run.pinnedBaseCommit||run.workerEvidence.pinnedBaseCommit!==run.pinnedBaseCommit||completedWorkers.length!==1||completedWorkers[0]?.id!==run.workerEvidence.workerAssignmentId||completedWorkers[0]?.responseId!==run.workerEvidence.responseId)throw Object.assign(new Error('Human decision requires evidence bound to the run pinned base and its sole completed Worker response'),{statusCode:409});
      if(input.evidenceCommit&&input.evidenceCommit!==run.workerEvidence.pinnedBaseCommit)throw Object.assign(new Error('Decision evidence commit must match the pinned Worker base'),{statusCode:409});
      const accepted={id:id('approval'),approved:input.approved,decision:input.approved?'approved' as const:'rejected' as const,evidenceCommit:run.workerEvidence.pinnedBaseCommit,rationale:input.rationale?.trim(),createdAt:now()};run.approval=accepted;run.workerEvidence.acceptance=input.approved?'accepted':'rejected';run.status=input.approved?'completed':'failed';
      s.events.push(event(input.approved?'run.human_approved':'run.human_rejected','run',run.id,{approvalId:accepted.id,recommendationId:run.reviewerRecommendation.id,decision:accepted.decision}));
      if(input.approved&&this.hindsight)for(const a of run.assignments.filter(a=>a.roleId==='worker'&&a.status==='succeeded'))s.events.push(event('memory.retention_intent','assignment',a.id,{retentionId:a.submissionId,idempotencyReference:`foreman-submission-${a.submissionId}`,status:'pending'}));
      return accepted;
    });
    // The durable approval and each retention intent are committed before this background work starts.
    if(this.hindsight)void this.resumePendingRetentions().catch(()=>{this.memoryServiceState='degraded';});
    return approval;
  }
  async resumePendingRetentions():Promise<void>{
    if(!this.hindsight)return;
    const state=await this.store.load();
    const completed=new Set(state.events.filter(e=>e.type==='memory.retention_completed').map(e=>String(e.data.retentionId)));
    const seen=new Set<string>();
    for(const intent of state.events.filter(e=>e.type==='memory.retention_intent')){
      const retentionId=String(intent.data.retentionId??'');if(!retentionId||completed.has(retentionId)||seen.has(retentionId))continue;seen.add(retentionId);
      for(const project of state.projects)for(const task of project.tasks)for(const run of task.runs){
        if(!run.approval?.approved)continue;
        const assignment=run.assignments.find(a=>a.id===intent.entityId&&a.roleId==='worker'&&a.status==='succeeded'&&a.submissionId===retentionId);
        if(assignment)void this.processRetention(project.id,task.id,run.id,assignment.id,retentionId);
      }
    }
  }
  private async processRetention(projectId:string,taskId:string,runId:string,assignmentId:string,retentionId:string):Promise<void>{
    if(!this.hindsight||this.retentionInFlight.has(retentionId))return;
    this.retentionInFlight.add(retentionId);
    try{
      const {a}=this.findAssignment(await this.store.load(),assignmentId);
      const retained=await this.hindsight.retainOutcome({projectId,submissionId:a.submissionId,runId,roleId:a.roleId,taskId,outcome:typeof a.result==='string'?a.result:JSON.stringify(a.result)??'',humanApproved:true});
      this.memoryServiceState=retained.status==='accepted'?'ready':'degraded';
      await this.store.mutate(s=>{s.events.push(event(retained.status==='accepted'?'memory.retention_completed':'memory.retention_attempt_failed','assignment',a.id,{retentionId,status:retained.status,bankId:retained.bankId,...(retained.operationId?{operationId:retained.operationId}:{}),...(retained.error?{error:retained.error}:{})}));});
    }catch(error){
      this.memoryServiceState='degraded';
      await this.store.mutate(s=>{s.events.push(event('memory.retention_attempt_failed','assignment',assignmentId,{retentionId,status:'degraded',error:error instanceof Error?error.message:String(error)}));}).catch(()=>undefined);
    }finally{this.retentionInFlight.delete(retentionId);}
  }
  private findTask(s:State,id:string) { for(const p of s.projects){const task=p.tasks.find(t=>t.id===id);if(task)return {project:p,task};} throw Object.assign(new Error('Task not found'),{statusCode:404}); }
  private findGuidanceRun(s:State,guidanceId:string):Run { for(const p of s.projects)for(const t of p.tasks)for(const r of t.runs)if(r.guidance.some(g=>g.id===guidanceId))return r;throw Object.assign(new Error('Guidance not found'),{statusCode:404}); }
  private findProject(s:State,taskId:string) { return this.findTask(s,taskId).project; }
  private findRun(s:State,id:string) { for(const p of s.projects)for(const t of p.tasks){const r=t.runs.find(r=>r.id===id);if(r)return r;} throw Object.assign(new Error('Run not found'),{statusCode:404}); }
  private findRunContext(s:State,id:string) { for(const p of s.projects)for(const t of p.tasks){const run=t.runs.find(r=>r.id===id);if(run)return {project:p,task:t,run};} throw Object.assign(new Error('Run not found'),{statusCode:404}); }
  private findAssignment(s:State,id:string) { for(const p of s.projects)for(const t of p.tasks)for(const run of t.runs){const a=run.assignments.find(a=>a.id===id);if(a)return {a,run};} throw Object.assign(new Error('Assignment not found'),{statusCode:404}); }
}
function normalizeStatus(status?:string): Assignment['status'] { if(status==='completed'||status==='succeeded') return 'succeeded'; if(status==='incomplete') return 'needs_revision'; if(status==='failed'||status==='running'||status==='cancelled'||status==='needs_revision') return status; return 'submitted'; }
function newSession(roleId:'planner'|'orchestrator',config:RoleConfig,generation=1):Run['sessions']['planner'] { return {localId:id(`${roleId}-session`),roleId,generation,status:'new',config:structuredClone(config),startedAt:now()}; }
interface GuidanceAck { guidanceId:string; action:'applied'|'replan'|'waiting'; reason:string }
function parseGuidanceAcknowledgments(value:unknown,expectedIds:string[]):GuidanceAck[]|undefined { if(typeof value!=='string')return;try{const parsed=JSON.parse(value) as {acknowledgments?:unknown};if(!parsed||!Array.isArray(parsed.acknowledgments)||parsed.acknowledgments.length!==expectedIds.length)return;const result:GuidanceAck[]=[];for(const item of parsed.acknowledgments){if(!item||typeof item!=='object')return;const x=item as Record<string,unknown>;if(typeof x.guidanceId!=='string'||!['applied','replan','waiting'].includes(String(x.action))||typeof x.reason!=='string'||!x.reason.trim())return;result.push({guidanceId:x.guidanceId,action:x.action as GuidanceAck['action'],reason:x.reason.trim().slice(0,1000)});}if(new Set(result.map(x=>x.guidanceId)).size!==expectedIds.length||expectedIds.some(id=>!result.some(x=>x.guidanceId===id)))return;return result;}catch{return;} }
const usageFields=['inputTokens','outputTokens','totalTokens','cachedInputTokens','runtimeMs','requestCount'] as const;
function aggregate(values:Array<Usage|undefined>):Usage|undefined {const measured=values.filter((x):x is Usage=>!!x&&Object.keys(x).some(k=>usageFields.includes(k as typeof usageFields[number])));if(!measured.length)return;const result:Usage={measured:true};for(const field of usageFields){const numbers=values.map(x=>x?.[field]);if(numbers.length&&numbers.every((x):x is number=>typeof x==='number'&&Number.isFinite(x)))result[field]=numbers.reduce((a,b)=>a+b,0);}return Object.keys(result).length>1?result:undefined;}
function groupUsage(assignments:Assignment[]):Record<string,Usage>|undefined {const groups=new Map<string,Array<Usage|undefined>>();for(const a of assignments){if(!a.actualConfig)continue;const key=`${a.actualConfig.harnessId}/${a.actualConfig.model}`;groups.set(key,[...(groups.get(key)??[]),a.usage]);}const result=Object.fromEntries([...groups.entries()].map(([key,values])=>[key,aggregate(values)]).filter(([,value])=>!!value));return Object.keys(result).length?result as Record<string,Usage>:undefined;}
