export type ProjectStatus = 'active' | 'archived';
export type TaskStatus = 'ready' | 'active' | 'blocked' | 'completed' | 'cancelled';
export type RunStatus = 'planning' | 'running' | 'waiting_guidance' | 'review' | 'validation' | 'awaiting_approval' | 'completed' | 'failed' | 'cancelled' | 'abandoned';
export type RoleKind = 'planner' | 'orchestrator' | 'worker' | 'reviewer';
export type AssignmentStatus = 'queued' | 'submitting' | 'submitted' | 'running' | 'cancel_requested' | 'cancelled' | 'succeeded' | 'failed' | 'needs_revision';
export type GuidanceStatus = 'queued' | 'delivered' | 'applied' | 'replan' | 'waiting' | 'cancelled';

export interface RoleConfig { harnessId: string; model: string; options?: Record<string, unknown> }
export interface Usage { inputTokens?:number; outputTokens?:number; totalTokens?:number; thinkingTokens?:number; cachedInputTokens?:number; runtimeMs?:number; requestCount?:number; measured?:true }
export interface Role { id: string; name: string; kind: RoleKind; enabled: boolean; config: RoleConfig; configSchema: Record<string, unknown>; availableConfigs: RoleConfig[]; usage?:Usage; usageByHarnessModel?:Record<string,Usage> }
export interface ProjectPlannerMessage { id:string; role:'user'|'planner'; text:string; createdAt:string; assignmentId?:string; createdTaskIds?:string[] }
export interface ProjectPlannerSession extends RoleSession { projectId:string }
export interface TaskSpec { title:string; goal:string; suggestedAllowedPaths:string[]; validationCriteria:string[]; dependsOn?:string[] }
export interface ApprovedTaskPlan { scope:string[]; roleConfigs:Record<string,RoleConfig>; validationCommands:Array<{name:string;command:string;args:string[];cwd?:string;network?:boolean}>; budgets:RunBudget; baseCommit?:string }
export interface TaskPlanApproval { status:'approved'; approvedAt:string; specDigest:string; plan:ApprovedTaskPlan; runId:string }
export interface Project { id: string; name: string; status: ProjectStatus; defaultRoleConfigs: Record<string, RoleConfig>; roleConfigOverridesMigrated?: true; createdAt: string; tasks: Task[]; plannerSession?:ProjectPlannerSession; plannerSessionHistory?:ProjectPlannerSession[]; plannerMessages?:ProjectPlannerMessage[]; plannerAssignments?:Assignment[]; usage?:Usage; usageByHarnessModel?:Record<string,Usage> }
export interface Task { id: string; title: string; goal?:string; suggestedAllowedPaths?:string[]; validationCriteria?:string[]; dependsOn?:string[]; planApproval?:TaskPlanApproval; status: TaskStatus; createdAt: string; runs: Run[] }
export interface RoleSession { localId: string; roleId: 'planner'|'orchestrator'; generation: number; status: 'new'|'active'|'rotated'; config: RoleConfig; uhpSessionId?: string; responseId?: string; startedAt: string; rotatedAt?: string }
export interface ReviewRecord { id: string; status:'proposed'|'verified'; reviewerAssignmentId: string; implementationAssignmentIds: string[]; verdict: 'clear'|'changes_requested'|'rejected'; scope: string[]; summary: string; createdAt: string }
/** Legacy records carry the complete result tree in `entries` and have no `snapshotFormat`. Records with `snapshotFormat:'base_plus_changes'` store only `changes` plus `completeSnapshot.entryCount`/`snapshotDigest`; the tree is `snapshotGitCommit(pinnedBaseCommit)` with `changes` applied (see `fullSnapshotEntries`). */
export interface WorkerEvidence { provenance:'bridge_snapshot'|'recorded_replay'|'recorded_live_import'; workerAssignmentId:string; responseId:string; requestedModel?:string; actualModel?:string; actualModelStatus?:'observed'|'unavailable'; cliInvocation?:{executable:string;hostExecutable?:string;args:string[]}; usage?:Usage; workspaceId?:string; pinnedBaseCommit:string; completeSnapshot:{reportedComplete:true;reportedErrors:0;entryCount:number;snapshotDigest?:string}; snapshotFormat?:'base_plus_changes'; scopeVerified:true; allowedScope:string[]; entries?:import('./workspace-snapshot.js').SnapshotEntry[]; changes:import('./workspace-snapshot.js').SnapshotChange[]; reviewDiff:string; /** Set when Foreman ran the configured format step over the Worker snapshot; `entries`/`changes` above are then the formatted bytes. */ formatting?:import('./format-step.js').WorkerFormatting; acceptance:'not_decided'|'accepted'|'rejected' }
export interface GitEvidence { status: 'unverified'|'verified'; commit?: string; tree?: string; changedPaths?: string[]; submittedAt: string }
export interface ValidationCheck { name:string; command:string; args:string[]; exitCode:number|null; signal?:string; timedOut:boolean; output:string; outputTruncated:boolean; startedAt:string; finishedAt:string; passed:boolean; sandbox?:'bwrap'|'none'; network?:boolean; /** Set only on a failed check once the same command ran against the unchanged pinned base: true when it fails there too, so the Worker cannot fix it. Never set on a passing check, so it is not part of any approved evidence. */ failsOnBase?:boolean }
/** Result of running the setup commands and the failed checks against the unchanged pinned base. Cached on the run by pinned base + command digest. */
export interface BaselineValidation { pinnedBaseCommit:string; commandDigest:string; ranAt:string; checks:Array<{name:string;passed:boolean;exitCode:number|null;timedOut:boolean}> }
export interface ValidationRecord { id: string; status:'unverified'|'passed'|'failed'; passed: boolean; reportedPassed:boolean; checks: Array<{name:string;passed:boolean;details?:string}>; observations?:ValidationCheck[]; resultGate?:{passed:boolean;reason:string}; policy?:{requireAllChecksPass:true;configuredCheckCount:number;commandDigest?:string}; gitEvidence?: GitEvidence; createdAt: string }
export interface ValidationProgressCheck { name:string; command:string; args:string[]; network?:boolean; status:'queued'|'running'|'passed'|'failed'; output:string; outputTruncated:boolean; startedAt?:string; finishedAt?:string; elapsedMs?:number; exitCode?:number|null; signal?:string; timedOut?:boolean }
export interface ValidationProgress { attemptId:string; startedAt:string; finishedAt?:string; checks:ValidationProgressCheck[] }
export interface ReviewerRecommendation { id:string; status:'proposed'; provenance:'uhp_response'|'simulated_fixture'; reviewerAssignmentId:string; harnessId:string; model:string; actualModel?:string; responseId:string; sessionId?:string; usage?:Usage; reviewMode?:'read_only'; mutationAttempted?:false; verdict:'recommend'|'request_changes'|'reject'; rationale:string; createdAt:string }
export interface ApprovalRecord { id: string; approved: boolean; decision:'approved'|'rejected'; evidenceCommit?:string; evidenceDigest?:string; rationale?:string; createdAt: string }
export interface PromotionRecord { status:'not_started'|'promoting'|'applied'|'failed'|'abandoned'; operationId?:string; evidenceDigest?:string; destinationBranch?:string; resultCommit?:string; resultTree?:string; error?:string; updatedAt:string }
export interface PrDraft { title: string; body: string; source: 'planner'|'template'|'edited'; generatedAt: string; assignmentId?: string; fallbackReason?: string }
export interface Run { id: string; status: RunStatus; createdAt: string; allowedScope?:string[]; baseFilePaths?:string[]; validationCommands?:Array<{name:string;command:string;args:string[];cwd?:string;network?:boolean}>; formatCommand?:{name:string;command:string;args:string[];cwd?:string;network?:boolean}; autoValidationCorrection?:boolean; validationProgress?:ValidationProgress; projectPlannerContext?:string; pinnedBaseCommit?:string; workspaceId?:string; controller?:RunControllerState; reviewerRetryAuthorized?:boolean; reviewerRecommendationHistory?:ReviewerRecommendation[]; plannerSessionId?: string; orchestratorSessionId?: string; sessions: {planner:RoleSession;orchestrator:RoleSession}; sessionHistory:RoleSession[]; roleConfigs: Record<string, RoleConfig>; guidance: Guidance[]; assignments: Assignment[]; workerProposal?:WorkerProposal; workerProposalHistory?:WorkerProposal[]; rejectedWorkerAttempts?:RejectedWorkerAttempt[]; orchestratorInbox?:OrchestratorResultInbox; orchestratorInboxHistory?:OrchestratorResultInbox[]; reviews:ReviewRecord[]; workerEvidence?:WorkerEvidence; workerEvidenceHistory?:WorkerEvidence[]; baselineValidation?:BaselineValidation; validation?:ValidationRecord; validationHistory?:ValidationRecord[]; reviewerRecommendation?:ReviewerRecommendation; approval?:ApprovalRecord; promotion?:PromotionRecord; prDraft?:PrDraft; usage?:Usage; usageByRole?:Record<string,Usage>; usageByHarnessModel?:Record<string,Usage> }
export interface RunBudget { roleTurns: Record<RoleKind, number>; workerAttempts: number }
export type RunBudgetOverrides = { roleTurns?: Partial<Record<RoleKind, number>>; workerAttempts?: number };
export interface RunControllerState { startedAt: string; active: boolean; phase:'orchestrating'|'dispatching'|'verifying'|'validating'|'reviewing'|'stopped'|'awaiting_approval'; budgets:RunBudget; stoppedReason?:string }
export interface WorkerProposal { id:string; status:'pending'|'dispatching'|'dispatched'; text:string; orchestratorAssignmentId:string; createdAt:string; targetFiles?:string[]; workerAssignmentId?:string; workerAssignmentHistoryIds?:string[]; workspaceId?:string; pinnedBaseCommit?:string }
export interface RejectedWorkerAttempt { id:string; proposal:WorkerProposal; workerAssignmentId:string; workspaceId?:string; pinnedBaseCommit?:string; responseId?:string; usage?:Usage; reason:string; evidenceStatus:'rejected_untrusted'; createdAt:string }
export interface OrchestratorResultInbox { id:string; status:'received'; runId:string; sessionLocalId:string; sessionId?:string; workerAssignmentId:string; workerResponseId:string; workerSessionId?:string; pinnedBaseCommit:string; allowedScope:string[]; reviewDiff:string; validation:{passed:boolean;resultGate?:ValidationRecord['resultGate'];policy?:ValidationRecord['policy'];observations:ValidationCheck[]}; evidenceDigest:string; receivedAt:string; deliveredInAssignmentId?:string }
export interface Guidance { id: string; sequence: number; text: string; status: GuidanceStatus; createdAt: string; plannerAssignmentId?:string; plannerReply?:string; checkpointHandoffAssignmentId?:string; acknowledgment?: 'applied'|'replan'|'waiting'; acknowledgedAt?: string }
export interface EmptyResponseInfo { reason: string; deniedTools?: string[] }
export interface RepoAccessRecord { mode: 'snapshot' | 'digest'; commit: string; reason?: string }
export interface Assignment { id: string; roleId: string; status: AssignmentStatus; requestedConfig: RoleConfig; requestedModel?:string; actualModelStatus?:'observed'|'unavailable'; selectedHarnessId?:string; reportedHarnessId?:string; modelFallback?:boolean; cliInvocation?:{executable:string;hostExecutable?:string;args:string[]}; actualConfig?: RoleConfig; configOutcome?:'confirmed'|'substituted'|'unavailable'; configNotes?:{boundsApplied?:boolean;ignoredFields?:string[]}; reviewerInboxId?:string; reviewerEvidenceDigest?:string; previousResponseRecoveryAttempted?:boolean; usage?:Usage; reviewerExecution?:{mode:string;mutationAttempted:boolean;validation?:unknown}; repoAccess?:RepoAccessRecord; prompt: string; submissionId: string; idempotencyKey: string; externalId?: string; sessionId?: string; responseId?: string; result?: unknown; error?: string; emptyResponse?: EmptyResponseInfo; createdAt: string; cancelIdempotencyKey?: string; createdTaskIds?:string[] }
export interface Event { id: string; type: string; entityType: string; entityId: string; at: string; data: Record<string, unknown>; seq?: number }
export interface State { version: 1; projects: Project[]; roles: Role[]; events: Event[]; eventSeq?: number }
export const now = (): string => new Date().toISOString();
export const id = (prefix: string): string => `${prefix}_${crypto.randomUUID()}`;

export function initialState(): State {
  return { version: 1, projects: [], events: [], roles: [
    { id: 'planner', name: 'Planner', kind: 'planner', enabled: false, config: { harnessId:'', model:'' }, availableConfigs: [], configSchema: { type: 'object', required: ['harnessId','model'] } },
    { id: 'orchestrator', name: 'Orchestrator', kind: 'orchestrator', enabled: false, config: { harnessId:'', model:'' }, availableConfigs: [], configSchema: { type: 'object', required: ['harnessId','model'] } },
    { id: 'worker', name: 'Worker', kind: 'worker', enabled: false, config: { harnessId:'', model:'' }, availableConfigs: [], configSchema: { type: 'object', required: ['harnessId','model'] } },
    { id: 'reviewer', name: 'Reviewer', kind: 'reviewer', enabled: false, config: { harnessId:'', model:'' }, availableConfigs: [], configSchema: { type: 'object', required: ['harnessId','model'] } },
  ] };
}

export function validateRoleConfig(role: Role, config: RoleConfig): void {
  if (!role.enabled) throw new Error(`Role ${role.id} is disabled`);
  if (!config || typeof config.harnessId !== 'string' || typeof config.model !== 'string') throw new Error('Role config requires harnessId and model');
  if (!role.availableConfigs.some(c => c.harnessId === config.harnessId && c.model === config.model)) throw new Error(`Unsupported ${role.id} config: ${config.harnessId}/${config.model}`);
}
