const TYPES=['fix','feat','chore','docs','refactor','test','build','ci','perf','style'] as const;
export type ConventionalType=typeof TYPES[number];

export function conventionalType(title:string,goal=''):ConventionalType{
  const explicit=title.trim().match(/^([a-z]+)(?:\([^)]*\))?:\s+/i)?.[1]?.toLowerCase();
  if(explicit&&TYPES.includes(explicit as ConventionalType))return explicit as ConventionalType;
  const subject=title.toLowerCase();
  if(/\b(doc|documentation|readme)\b/.test(subject))return 'docs';
  if(/\b(test|spec|coverage)\b/.test(subject))return 'test';
  if(/\b(refactor|cleanup|restructure)\b/.test(subject))return 'refactor';
  if(/\b(fix|bug|broken|crash|error|regression)\b/.test(subject))return 'fix';
  if(/\b(performance|faster|optimi[sz])\b/.test(subject))return 'perf';
  if(/\b(ci|workflow|pipeline)\b/.test(subject))return 'ci';
  if(/\b(add|support|create|implement|introduce|feature|improve|update)\b/.test(subject))return 'feat';
  const context=goal.toLowerCase();
  if(/\b(doc|documentation|readme)\b/.test(context))return 'docs';
  if(/\b(test|spec|coverage)\b/.test(context))return 'test';
  if(/\b(refactor|cleanup|restructure)\b/.test(context))return 'refactor';
  if(/\b(fix|bug|broken|crash|error|regression)\b/.test(context))return 'fix';
  if(/\b(performance|faster|optimi[sz])\b/.test(context))return 'perf';
  if(/\b(ci|workflow|pipeline)\b/.test(context))return 'ci';
  if(/\b(build|dependency|upgrade|package)\b/.test(context))return 'build';
  if(/\b(add|support|create|implement|introduce|feature|improve|update)\b/.test(context))return 'feat';
  return 'chore';
}

export function conventionalTitle(title:string,goal=''):string{
  const clean=title.trim().replace(/^foreman\s+(?:result|run)\s+/i,'').replace(/[.!]+$/,'').replace(/\s+/g,' ');
  const type=conventionalType(title,goal);
  const scope=clean.match(/^(?:fix|feat|chore|docs|refactor|test|build|ci|perf|style)(\([^)]*\))?:\s*/i)?.[1]??'';
  const subject=clean.replace(/^(?:fix|feat|chore|docs|refactor|test|build|ci|perf|style)(?:\([^)]*\))?:\s*/i,'').replace(/^run[_-]?[a-z0-9-]+$/i,'');
  return `${type}${scope}: ${subject||'update project'}`.slice(0,72).replace(/[.!]+$/,'');
}

export function resultBranchName(title:string,goal:string,runId:string):string{
  const slug=title.toLowerCase().replace(/^(?:fix|feat|chore|docs|refactor|test|build|ci|perf|style)(?:\([^)]*\))?:\s*/,'').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,48).replace(/-+$/,'')||'result';
  return `${conventionalType(title,goal)}/${slug}-${runId.replace(/[^a-z0-9]/gi,'').slice(-8).toLowerCase()}`;
}

export function conventionalCommitMessage(title:string,goal:string):string{
  return conventionalTitle(title,goal).toLowerCase().replace(/\s+/g,' ').slice(0,72);
}

export function promotionCommitMessage(existing:{operationId?:string;commitMessage?:string}|undefined,title:string,goal:string,runId:string):string{
  if(existing?.commitMessage)return existing.commitMessage;
  if(existing?.operationId)return `Foreman approved result ${runId}`;
  return conventionalCommitMessage(title,goal);
}

export function stripAutomationAttribution(body:string):string{return body.split(/\r?\n/).filter(line=>!/^\s*(?:generated by foreman\b|foreman run [A-Za-z0-9_-]+\s*[·|—-]|this (?:pull request|pr) was generated by foreman\b)/i.test(line)).join('\n').trim();}
